---
fontsize: 11pt
geometry: top=2cm, bottom=2cm, left=1.5cm, right=1.5cm,headsep=1cm
header-includes:
- \usepackage[utf8]{inputenc}
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \fancyfoot{}
- \usepackage{ragged2e}
- \linespread{1.15}
- \usepackage{float}
output: pdf_document
fig_caption: yes
keep_tex: yes
---
  
```{r set_libraries, include=FALSE, warning=FALSE}
#Libraries used in the r code
if (!require(pacman)){
  install.packages("pacman", repos="http://ftp.ussg.iu.edu/CRAN/")
  library(pacman)
}
p_load(kableExtra, sqldf, RODBC, dplyr)

#special for this script
p_load(ggplot2, ggrepel, mapplots, shapefiles, maptools)

'%!in%' <- function(x,y)!('%in%'(x,y)) #a "NOT in" statement

```

```{r set_parameters, include=FALSE}

# y1 <- @paramYear1
# y2 <- @paramYear2
# species <- c(@paramSpecies)
# areas <- c(@paramArea)
# size1 <- c(@paramSize1)
# size2 <- c(@paramSize2)


# Paramters to use in R
y1 <- 2021
y2 <- 2021
species <- c("SIL")
areas <- c(21)
size1 <- 250
size2 <- 300


#get shapefiles for the map
invisible(coast <- read.shapefile('Q:/gis/Dynamisk/GEOdata/BasicLayers/CoastLines/Europe/europe'))
invisible(dk_eez <- read.shapefile('Q:/gis/Dynamisk/GEOdata/BasicLayers/Boundaries/EEZ/LandAndSea/eez_dk_LandAndSea_2019'))

# invisible(coast <- read.shapefile('europe'))
# invisible(dk_eez <- read.shapefile('eez_dk_LandAndSea_2019'))


```


```{r get_data, include=FALSE}

channel <- odbcConnect("FishLineDW")

animal <- sqlQuery(channel, paste("SELECT     animalId, year, quarterGearStart AS quarter,
                                              cruise, trip, station, dfuArea AS area, speciesCode, 
                                              speciesListId, 
                                              number, weight, length AS length_mm, 
                                              remark AS remark_animal
                                     FROM     animal
                                     WHERE    (speciesCode IN ('", paste(species,collapse = "','"),"')) AND 
                                  	  	      (dfuArea IN ('", paste(areas,collapse = "','"),"')) AND 
                                              (year between ",y1," and ",y2," ) AND
                                              (individNum != 0)
                                        ORDER BY dateGearStart
                                			        ", sep = ""))

l_fish <- animal[animal$length_mm >= size1 & animal$length_mm <= size2, ]
cruise <- unique(l_fish$cruise)
trip <- unique(l_fish$trip)
station <- unique(l_fish$station)

if (nrow(l_fish) > 0) {
  samples <- sqlQuery(channel, paste("SELECT   year, cruise, trip, tripType, station,
                                             dateGearStart AS haul_start, dateGearEnd AS haul_end,
                                             latPosStartDec, lonPosStartDec, 
                                             latPosEndDec, lonPosEndDec
                                   FROM      Sample
                                   WHERE     (year between ",y1," and ",y2," ) AND 
                                  	  	     (cruise IN ('", paste(cruise,collapse = "','"),"')) AND  
                                  	  	     (trip IN ('", paste(trip,collapse = "','"),"')) AND
                                  	  	     (station IN ('", paste(station,collapse = "','"),"'))
                                			       ", sep = ""))
}

close(channel)

```

```{r export table, include=FALSE}
if (nrow(l_fish) > 0) {
  # ##Output fish-age information
  l_fish$FromFL <- "TRUE"
  
  out <- data.frame(sampleId = l_fish$animalId,
                    FromFL = l_fish$FromFL,
                    cruise = NA,
                    trip = NA,
                    station = NA,
                    catchDate = NA,
                    AreaCode = NA,
                    statisticalRectangle = NA, 
                    species = NA,
                    stock = NA,
                    lengthMM = NA,
                    weightG = NA,
                    sexCode = NA,
                    maturityIndexMethod  = NA,
                    maturityIndex = NA,
                    otolithReadingRemark = NA,
                    preparationMethod = NA,
                    lightType = NA,
                    otolithDescription = NA, 
                    edgeStructure = NA,
                    latPosStartText = NA,
                    lonPosStartText = NA,
                    createdBy = NA, 
                    imageName = NA,
                    comments = NA)
  
  write.csv2(out, paste0("Length_select_", format(Sys.Date(), "%d%m%y"), ".csv"),
            quote = FALSE, row.names = FALSE, na = '')
  
  # write.csv2(age_fish, file = "Q:/dfad/users/jostou/home/21_11_11_Julie_reports/results/table.csv",
  #            quote = FALSE, row.names = FALSE, na = '')
} else{
  print("Ingen Fisk i valgte Område og Længdekattegori")
}


```

\thispagestyle{empty}

\vspace*{1cm} 

\textbf{\huge Oversigt over hentet data}

\vspace{1cm}   

\textbf{\LARGE  Periode: `r y1` - `r y2` }\

\textbf{\LARGE  Art: `r species`. }\

\textbf{\LARGE  Område: `r areas`. }\

\textbf{\LARGE  Størelse: fra og med `r size1` til og med `r size2`. }\


\newpage

\section{Hvor er stationerne}
```{r station_plot, echo=FALSE, results='asis', cache=FALSE, message=FALSE, warning=FALSE, fig.width=12, fig.height=12}

if (nrow(l_fish) > 0) {
  #define the map outline
  #setting coordinates for aspect ration:
  asp <- 1/1
  
  xlim <- c(floor(min(samples$lonPosStartDec)),ceiling(max(samples$lonPosStartDec)))
  
  y_l <- ((xlim[2] - xlim[1])/asp)/2
  y_max <- ceiling(max(samples$latPosStartDec)/0.5)*0.5
  
  if (y_max - y_l < min(samples$latPosStartDec)){
    
    ylim <- c(y_max - y_l, y_max)
    
  } else {
    
    ylim <- c(floor(min(samples$latPosStartDec)/0.5)*0.5,ceiling(max(samples$latPosStartDec)/0.5)*0.5)
    xlim <- c(floor(min(samples$lonPosStartDec)),ceiling(max(samples$lonPosStartDec)))
    
  }
  
  
  
  #make the plot using the mapplots pakage
  p1 <- basemap(xlim, ylim)+
                draw.shape(coast, col="cornsilk")+
                draw.shape(dk_eez, col="transparent", border = "red")+
                draw.rect()+
                points(samples$lonPosStartDec, samples$latPosStartDec, col="green", pch = 16, cex = 1.5)
                pointLabel(x=samples$lonPosStartDec,  y= samples$latPosStartDec,
                           labels=as.character(samples$cruise),
                           cex=1,offset=-1, allowSmallOverlap = FALSE)
}

              
```








