---
fontsize: 8pt
geometry: top=0.6in, bottom=0.6in, left=0.3in, right=0.3in
header-includes:
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage{microtype}
- \usepackage[T1]{fontenc}
- \usepackage[danish]{babel}
- \usepackage[utf8]{inputenc}
- \usepackage{graphicx}
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \fancyhf{}
- \usepackage{fullwidth}
- \usepackage[table]{xcolor}
- \usepackage{ragged2e}
- \usepackage{catchfile}
- \usepackage{array}
- \usepackage[export]{adjustbox}
- \usepackage{multirow}
- \linespread{1.3}
- \usepackage{tabularx}
- \usepackage[labelformat=empty]{caption}
output: pdf_document
classoption: landscape
---

\renewcommand{\familydefault}{\sfdefault}
\sffamily



```{r set_libraries, include=FALSE}

# LIBRARIES ###################################################################

# Libraries
if (!require(pacman)){
  install.packages("pacman", repos="http://ftp.ussg.iu.edu/CRAN/")
  library(pacman)
}
p_load(sqldf,RODBC,xtable,maptools,date,lubridate,data.table,tidyr,ggplot2,
       scales,grid,dplyr)
# if (!require(sqldf)){
#   install.packages("sqldf", repos="http://ftp.ussg.iu.edu/CRAN/")
#   library(sqldf)
# }
# if (!require(RODBC)){
#   install.packages("RODBC", repos="http://ftp.ussg.iu.edu/CRAN/")
#   library(RODBC)
# }
# # if (!require(plyr)){
# #   install.packages("plyr", repos="http://ftp.ussg.iu.edu/CRAN/")
# #   library(plyr)
# # }
# if (!require(xtable)){
#   install.packages("xtable", repos="http://ftp.ussg.iu.edu/CRAN/")
#   library(xtable)
# }
# if (!require(maptools)){
#   install.packages("maptools", repos="http://ftp.ussg.iu.edu/CRAN/")
#   library(maptools)
# }
# if (!require(date)){
#   install.packages("date", repos="http://ftp.ussg.iu.edu/CRAN/")
#   library(date)
# }
# if (!require(lubridate)){
#   install.packages("lubridate", repos="http://ftp.ussg.iu.edu/CRAN/")
#   library(lubridate)
# }
# if (!require(data.table)){
#   install.packages("data.table", repos="http://ftp.ussg.iu.edu/CRAN/")
#   library(data.table)
# }
# if (!require(tidyr)){
#   install.packages("tidyr")
#   library(tidyr)
# }
# if (!require(ggplot2)){
#   install.packages("ggplot2", repos="http://ftp.ussg.iu.edu/CRAN/")
#   library(ggplot2)
# }
# if (!require(scales)){
#   install.packages("scales", repos="http://ftp.ussg.iu.edu/CRAN/")
#   library(scales)
# }
# if (!require(grid)){
#   install.packages("grid", repos="http://ftp.ussg.iu.edu/CRAN/")
#   library(grid)
# }
# if (!require(dplyr)){
#   install.packages("dplyr", repos="http://ftp.ussg.iu.edu/CRAN/")
#   library(dplyr)
# }


```

```{r define_input, echo=FALSE}

# INPUT PARAMETERS ############################################################
#
# cruise_all <- c("BITS")
# v_cruise <- c("BITS-1","BITS-2")
# # cruise_all <- c("TBM")
# # v_cruise <- c("Tobisskrabetogt LH.")
# v_year <- c("2018","2017")
# art_out <- c("TBM")
# 
# cruise_all <- c("TNG")
# v_cruise <- c('Tunger')
# v_year <- c("2018")
# art_out <- c()

cruise_all <- c(@paramCruise1)
v_cruise <- c(@paramCruise2)
v_year <- c(@paramYear)
art_out <- c(@paramSpecies)

# cruise_all <- c("BITS")
# v_cruise <- c("BITS-2")
# v_year <- c("2012")
# # # art_out <- c("TBM")
# channel <- odbcConnect("FishLineDW")
# art_out <- sqlQuery(channel, sprintf("SELECT slr.speciesCode
# FROM FishLineDW.dbo.SpeciesList slr
# LEFT OUTER JOIN FishLine.dbo.L_Species s ON s.speciesCode = slr.speciesCode
# WHERE slr.year IN (%s)
#   AND slr.cruise IN ('%s')
#   AND slr.speciescode NOT IN ('INV', 'DTO', 'AF1', 'AF2', 'AF3',
# 							  'AF4', 'AF5', 'AAA', 'AAG', 'ANA',
# 							  'ANM', 'FED', 'SKL', 'TAN', 'UBS')
# GROUP BY slr.speciesCode
# ORDER BY slr.speciesCode", v_year,paste(v_cruise,collapse=("','"))),stringsAsFactors=F)
# close(channel)
# art_out <- art_out$speciesCode

# cruise_all <- c("TBM")
# v_cruise <- c("REYKJANES","Salling","Tobisskrabetogt LH.")
# v_year <- c("2018","2017")
# art_out <- c("TBM")

```

```{r functions, include=FALSE}

# SIMPLE UD FUNCTIONS #########################################################

# Function if na = -9
ifelse_na <- function(var) {
  ifelse(!is.na(var),var,-9)
}

# Rounding
round2 = function(x) trunc(x+0.5)

```

```{r collect_data, echo=FALSE,include=FALSE,cache=FALSE}

# COLLECT DATA FOR HH, HL AND CA ##############################################

channel <- odbcConnect("FishLineDW")

# HH
hh1_a <- sqlQuery(channel, paste0(

  "SELECT    s.*, t.platform1
  FROM      Trip AS t LEFT OUTER JOIN
  Sample AS s ON s.tripId = t.tripId
  WHERE     s.year IN ('", paste(v_year, collapse = "','"), "') AND
  s.cruise IN ('", paste(v_cruise, collapse = "','"), "') AND
  s.sampleId NOT IN (37510,37511) AND
  s.latPosStartDec is not null AND
  s.lonPosStartDec is not null
  ORDER BY  s.station "
), stringsAsFactors = FALSE)

# HLCA
hlca_a <- sqlQuery(channel, paste0(

  "SELECT  sl.speciesListId, sl.sampleId, sl.year, sl.quarterGearStart,
  sl.dateGearStart, sl.cruise, sl.trip, sl.tripType,
  sl.station,sl.dfuArea, sl.statisticalRectangle, sl.gearType,
  sl.meshSize,sl.speciesCode, sl.landingCategory,
  sl.dfuBase_Category, sl.sizeSortingEU, sl.sizeSortingDFU,
  sl.ovigorous, sl.cuticulaHardness, sl.treatment,
  sl.weightStep0, sl.weightStep1, sl.weightStep2,
  sl.weightStep3, sl.landingWeightStep0, sl.landingWeightStep1,
  sl.raisingFactor, sl.remark, an.speciesList_sexCode,
  an.representative, an.individNum, an.length,
  an.lengthMeasureUnit, an.sexCode, an.number AS Animal_number,
  an.weight, an.maturityIndex, an.maturityIndexMethod, a.age,
  a.number AS Age_Number
  FROM    Age AS a RIGHT OUTER JOIN
  Animal AS an RIGHT OUTER JOIN
  SpeciesList AS sl ON an.speciesListId = sl.speciesListId
  ON a.animalId = an.animalId
  WHERE   sl.year IN ('", paste(v_year, collapse = "','"), "')  AND
  sl.cruise IN ('", paste(v_cruise, collapse = "','"), "') AND
  sl.speciesCode NOT IN ('INV', 'DTO', 'AF1', 'AF2', 'AF3',
  'AF4', 'AF5', 'AAA', 'AAG', 'ANA',
  'ANM', 'FED', 'SKL', 'TAN', 'UBS')"
), stringsAsFactors=FALSE)


# COLLECT SPECIES INFO ########################################################

species <- sqlQuery(channel, paste0(
  "SELECT  *
  FROM    L_Species"), stringsAsFactors=FALSE)


close(channel)

```

```{r data_corrections, include = FALSE}

# DATA CORRECTIONS ############################################################

# The sandeel dredge survey "Salling" in 2012 is a commercial
# survey which we cannot use for scientific studies
hh1_a <- hh1_a[!(hh1_a$year == 2012 & hh1_a$cruise == "Salling"),]
hlca_a <- hlca_a[!(hlca_a$year == 2012 & hlca_a$cruise == "Salling"),]

hlca_a[hlca_a$sexCode == "T" & !is.na(hlca_a$sexCode), "sexCode"] <- "H"

# On IBTS-2 in 1996 we need to remove some test stations
hlca_a <- hlca_a[!(hlca_a$station %like% '^OMR' | hlca_a$station == 'TEST'),]
hh1_a <- hh1_a[!(hh1_a$station %like% '^OMR' | hh1_a$station == 'TEST'),]

hlca <- hlca_a


```



```{r setup1, echo=FALSE, include=FALSE, cache=FALSE}
# SURVEY VARIABLE #############################################################

# survey variable needed for cruise dependent settings
if (any(v_cruise %in% c("IBTS-1", "IBTS-2"))) {survey <- "NS-IBTS"}
if (any(v_cruise %in% c("BITS-1", "BITS-2"))) {survey <- "BITS"}
if (any(toupper(v_cruise) %in% c("KASU-1", "KASU-2","FISHHABIT"))) {survey <- "KASU"}
if (any(toupper(v_cruise) %in% c("TUNGER"))) {survey <- "TN" }
if (any(toupper(v_cruise) %in% c('2262-TORSK', 'TORSK'))) {survey <- 'TOR' }
if (any(toupper(v_cruise) %in% c('E349', 'E562', 'L151', 'R500', 'L610',
                        # 'Reyklanes','Reykjanes',
                        "REYKJANES",'REYKLANES','LONNY HEDVIG',
                        'SALLING')) ||
    grepl("TOBISSKRABETOGT",toupper(v_cruise))) {survey <- 'TBM'}
# if (){survey <- 'TBM'}
if (any(v_cruise %like% "BV +")){survey <- 'MS'}


# HAUL NUMBER #################################################################

# Create consecutive haul number
hh1_b <- hh1_a[order(as.integer(hh1_a$dateGearStart)),]
if (survey %in% c("MS")){

  # hh1_b <- ddply(hh1_b,
  #                c("year", "quarterGearStart", "platform1","gearType","station"),
  #                transform,
  #                HaulNo = seq_along(dateGearStart))
    hh1_b <- hh1_b %>% 
      group_by(year,quarterGearStart,platform1,gearType,station) %>% 
      mutate(HaulNo = seq_along(dateGearStart)) %>% 
      data.frame()
  # HaulNo = sampleId)

}else{
  # hh1_b <- ddply(hh1_b,
  #                c("year", "cruise", "trip"),
  #                transform,
  #                HaulNo = seq_along(dateGearStart))
  hh1_b <- hh1_b %>% 
    group_by(year,cruise,trip) %>% 
    mutate(HaulNo = seq_along(dateGearStart)) %>% 
    data.frame()
}

```


```{r sunrise_sunset, echo=FALSE, include=FALSE, cache=FALSE}

# DAY OR NIGHT VARIABLE #######################################################

# Determine if "Day" or "Night" haul for NS-IBTS, BITS and KASU

if (survey %in% c("BITS","NS-IBTS","KASU")) {


  # Collect data
  channel <- odbcConnect("FishLineDW")
  positionDate0 <- sqlQuery(channel, paste0(

    "SELECT    sampleId, DATEPART(year, dateGearStart) AS Year,
    DATEPART(month, dateGearStart) AS Month,
    DATEPART(day, dateGearStart) AS Day,
    lonPosStartDec, latPosStartDec
    FROM      Sample
    WHERE     year IN ('", paste(v_year,collapse = "','"),"') AND
    cruise IN ('", paste(v_cruise,collapse = "','"),"') AND
    station not like '%OMR%' AND station!='TEST' AND
    sampleId NOT IN (37510,37511)
    ORDER BY  sampleId  "), stringsAsFactors=FALSE)

  close(channel)

  positionDate <- positionDate0[!is.na(positionDate0$lonPosStartDec) &
                                  !is.na(positionDate0$latPosStartDec),]

  # Haul dates and positions
  temp <- mdy.date(month = positionDate$Month, day = positionDate$Day,
                   year = positionDate$Year)
  dates <- as.POSIXct(temp, TZ = 'GMT')
  crds <- SpatialPoints(positionDate[, c("lonPosStartDec", "latPosStartDec")],
                        proj4string = CRS("+proj=longlat +datum=WGS84"),
                        bbox = NULL)

  # Get time of sunrise and sunset on haul dates
  sunRise <- sunriset(crds, dates, direction = "sunrise", POSIXct.out = TRUE)
  sunSet <- sunriset(crds, dates, direction = "sunset", POSIXct.out = TRUE)

  # Combine with sample ID
  sun <- data.frame("sampleId" = positionDate$sampleId,
                    "sunRiseGMT" = sunRise$time,
                    "sunSetGMT" = sunSet$time )


  # Time 15 or 25 min before/after sunrise/set
  sun_int <- ifelse(survey %in% c("BITS", "KASU"), 15, 25)

  # Get times sun_int (15 or 25) minutes before sunrise and
  # sun_lint minutes after sunset
  sun$sunRiseGMTint <- sun$sunRiseGMT - (60*sun_int) - second(sun$sunRiseGMT)
  sun$sunSetGMTint <- sun$sunSetGMT + (60*sun_int) - second(sun$sunSetGMT)


  ### MERGE WITH DATA HH ###
  hh1_c <- merge(hh1_b, sun[, c("sampleId", "sunRiseGMTint", "sunSetGMTint")])

  # Get time of midway through haul
  hh1_c$DN_check <- hh1_c$dateGearStart+(hh1_c$fishingtime*60)/2

  # If time of hauls (DN_check) is after sunrise and before sunset
  # then DayNight = D(ay) else N(ight) - with sun_int af buffer
  hh1_c$DayNight <- ifelse(hh1_c$sunRiseGMTint <= hh1_c$DN_check &
                             hh1_c$DN_check <= hh1_c$sunSetGMTint, "D", "N")


} else {
  # If not want day/night variable
  hh1_c <- hh1_b
  hh1_c$DayNight <- "-9"
}

# Defne new variable
hh1 <- hh1_c

```


```{r variablesCorrections, echo=FALSE, include=FALSE, cache=FALSE}

# DATA HH #####################################################################

# Re-naming and defining new variables
setnames(hh1, old = c('station', 'fishingtime','latPosStartDec','lonPosStartDec',
                      'latPosEndDec','lonPosEndDec','statisticalRectangle'),
         new = c('StNo','HaulDur', 'ShootLat', 'ShootLong',
                 'HaulLat','HaulLong','StatRec'))

hh2 <- cbind(hh1, survey = survey, country = "DEN",
             month = month(hh1$dateGearStart), day = day(hh1$dateGearStart),
             Tickler = -9, StdSpecRecCode = '1', BycSpecRecCode = '1',
             Rigging <- '-9', Gear = "", SweepLngt = NA, SweepLngt = NA,
             GearExp = "", DoorType = "", Warpdia = NA, WarpDen = NA,
             DoorSurface = NA, DoorWgt = NA, Buoyancy = NA, KiteDim = NA,
             WgtGroundRope = NA, stringsAsFactors = FALSE)


# Ship -----------------------------------------------------------

# Ship
hh2[hh2$survey %in% c("BITS", "NS-IBTS"), "ship"] <- "DAN2"
hh2[hh2$survey == "KASU" & hh2$year >= 2016, "ship"] <- "26HF"
hh2[hh2$survey == "KASU"  & hh2$year < 2016, "ship"] <- "HAF"
hh2[!(hh2$survey %in% c("NS-IBTS","KASU","BITS")), "ship"] <-
  hh2[!(hh2$survey %in% c("NS-IBTS", "KASU", "BITS")),]$platform1


# Depth and stratum -----------------------------------------------------------

# Depth
hh2$Depth <- ifelse(!is.na(hh2$depthAvg), round2(hh2$depthAvg), -9)

# Stratum (only BITS and KASU)
if (survey %in% c("KASU","BITS")) {
  hh2[hh2$Depth > 0 & hh2$Depth < 20, "stratum"] <- "8"
  hh2[hh2$Depth >= 20 & hh2$Depth < 40, "stratum"] <- "9"
  hh2[hh2$Depth >= 40 & hh2$Depth < 60, "stratum"] <- "10"
  hh2[hh2$Depth >= 60 & hh2$Depth < 80, "stratum"] <- "11"
  hh2[hh2$Depth >= 80 & hh2$Depth < 100, "stratum"] <- "12"
  hh2[hh2$Depth >= 100 & hh2$Depth < 120, "stratum"] <- "13"
  hh2[hh2$Depth >= 120 & hh2$Depth < 200, "stratum"] <- "14"
  hh2[is.na(hh2$Depth), "stratum"] <- "-9"
} else {
  hh2$stratum <- "-9"
}

# Time of haul ----------------------------------------------------------------

hh2[hour(hh2$dateGearStart) < 10,"hour_start"] <-
  paste0("0",hour(hh2[hour(hh2$dateGearStart) < 10,]$dateGearStart))
hh2[hour(hh2$dateGearStart) >= 10,"hour_start"] <-
  hour(hh2[hour(hh2$dateGearStart) >= 10,]$dateGearStart)
hh2[minute(hh2$dateGearStart) < 10,"minute_start"] <-
  paste0("0",substr(minute(hh2[minute(hh2$dateGearStart)
                               < 10,]$dateGearStart),1,2))
hh2[minute(hh2$dateGearStart) >= 10,"minute_start"] <-
  minute(hh2[minute(hh2$dateGearStart) >= 10,]$dateGearStart)
hh2$TimeShot <- paste0(hh2$hour_start,hh2$minute_start)

# Haul type -------------------------------------------------------------------

# Haul value and data type
hh2[hh2$gearQuality=='I' & !is.na(hh2$gearQuality),"HaulVal"] <- "I"
hh2[hh2$gearQuality=='V' & !is.na(hh2$gearQuality),"HaulVal"] <- "V"
if (survey %in% c("KASU","BITS")) {
  hh2[hh2$haulType=='X' & !is.na(hh2$haulType),"HaulVal"] <- "A"
  hh2[hh2$haulType=='K' & !is.na(hh2$haulType),"HaulVal"] <- "C"
  hh2[hh2$gearQuality=='V' & hh2$haulType=='N' & !is.na(hh2$gearQuality)
      & !is.na(hh2$haulType),"HaulVal"] <- "N"
  hh2[hh2$gearQuality=='V' & hh2$haulType=='Expo' & !is.na(hh2$gearQuality)
      & !is.na(hh2$haulType),"HaulVal"] <- "M"

}
#Kibi - rettet 10/01/2018 - var før i {} ovenfor, men så kom det ikke med videre
hh2$DataType <- ifelse(hh2$HaulVal=='N', "C", "R")

# Dimensions and CTD ----------------------------------------------------------

# CTD station
hh2$HydroStNo <- ifelse_na(hh2$hydroStnRef)

# Distance between start and end positions in meters
hh2$Distance <- ifelse(!is.na(hh2$courseTrack), hh2$courseTrack,
                       ifelse(!is.na(hh2$distancePositions),
                              round2(hh2$distancePositions*1000/0.539612),-9))

# Dimensions
hh2$WarpLngt <- ifelse_na(hh2$wireLength)
hh2$DoorSpread <- ifelse(hh2$gearType=="AKU",-9,ifelse_na(hh2$otterBoardDist))
hh2[is.na(hh2$netOpening),"netOpening"] <- -9


# Current, wind, waves and hydrografi -----------------------------------------

# New variables, if na set to -9
hh2$TowDir <- ifelse_na(hh2$haulDirection)
hh2$GroundSpeed <- ifelse_na(hh2$haulSpeedBot)
hh2$SpeedWater <- ifelse_na(hh2$haulSpeedWat)
hh2$SurCurDir <- ifelse_na(hh2$currentDirectionSrf)
hh2$SurCurSpeed <- ifelse_na(hh2$currentSpeedSrf)
hh2$BotCurDir <- ifelse_na(hh2$currentDirectionBot)
hh2$BotCurSpeed <- ifelse_na(hh2$currentSpeedBot)
hh2$WindDir <- ifelse_na(hh2$windDirection)
hh2$SwellDir <- ifelse_na(hh2$waveDirection)
hh2$SwellHeight <- ifelse_na(hh2$waveHeigth)

hh2[is.na(hh2$windSpeed),"windSpeed"] <- -9
hh2[is.na(hh2$wingSpread),"wingSpread"] <- -9
hh2[is.na(hh2$thermoCline),"thermoCline"] <- -9

hh2$SurTemp <- ifelse_na(hh2$temperatureSrf)
hh2$BotTemp <- ifelse_na(hh2$temperatureBot)
hh2$SurSal <- ifelse_na(hh2$salinitySrf)
hh2$BotSal <- ifelse_na(hh2$salinityBot)
hh2$ThClineDepth <- ifelse_na(hh2$thermoClineDepth)

# Gear specific information ---------------------------------------------------
# BITS values
if (cruise_all=="BITS"){
  hh2$Warpdia <- 20
  hh2$WarpDen <- 1.5817
  hh2$WgtGroundRope <- -9
}


for (i in 1:nrow(hh2)) {
  # BITS
  if (hh2$survey[i]=='BITS' & hh2$gearType[i]=='TV3' & !is.na(hh2$gearType[i]) ) {
    hh2$Gear[i] <- 'TVL' ; hh2$SweepLngt[i] <- -9; hh2$GearExp[i] <- "S";
    hh2$DoorType[i] <- "T"; hh2$WarpDen[i] <- -9; hh2$Warpdia[i] <- -9;
    hh2$DoorSurface[i] <- 4.4; hh2$DoorWgt[i] <- 520; hh2$Buoyancy[i]<- 213;
    hh2$KiteDim[i] <- -9; hh2$WgtGroundRope[i] <- -9
  } else if (hh2$survey[i]=='BITS' & hh2$gearType[i]=='TV3ROC' & !is.na(hh2$gearType[i])) {
    hh2$Gear[i] <- 'TVL' ; hh2$SweepLngt[i] <- -9; hh2$GearExp[i] <- "R";
    hh2$DoorType[i] <- "T"; hh2$WarpDen[i] <- -9; hh2$Warpdia[i] <- -9 ;
    hh2$DoorSurface[i] <- 4.4; hh2$DoorWgt[i] <- 520; hh2$Buoyancy[i]<- 213;
    hh2$KiteDim[i] <- -9; hh2$WgtGroundRope[i] <- -9
  } else if (hh2$survey[i]=='BITS' & hh2$gearType[i]=='Expo' & !is.na(hh2$gearType[i])) {
    hh2$Gear[i] <- 'EXP' ; hh2$SweepLngt[i] <- -9; hh2$GearExp[i] <- "S";
    hh2$DoorType[i] <- "T"; hh2$WarpDen[i] <- -9; hh2$Warpdia[i] <- -9;
    hh2$DoorSurface[i] <- 4.4; hh2$DoorWgt[i] <- 520; hh2$Buoyancy[i]<- -9;
    hh2$KiteDim[i] <- -9; hh2$WgtGroundRope[i] <- -9
  } else if (hh2$survey[i]=='BITS' & hh2$gearType[i]=='AKU' & !is.na(hh2$gearType[i])) {
    hh2$Gear[i] <- 'TVL' ; hh2$SweepLngt[i] <- -9; hh2$GearExp[i] <- "S";
    hh2$DoorType[i] <- "T"; hh2$WarpDen[i] <- -9; hh2$Warpdia[i] <- -9;
    hh2$DoorSurface[i] <- 4.4; hh2$DoorWgt[i] <- 520; hh2$Buoyancy[i]<- 213;
    hh2$KiteDim[i] <- -9; hh2$WgtGroundRope[i] <- -9
    # KASU
  } else if (hh2$survey[i]=='KASU' & hh2$gearType[i] %in% c('OTB','TV3') & !is.na(hh2$gearType[i])) {
    hh2$Gear[i] <- 'TVS'; hh2$SweepLngt[i] <- -9; hh2$GearExp[i] <- "S";
    hh2$DoorType[i] <- "-9"; hh2$WarpDen[i] <- -9; hh2$Warpdia[i] <- -9;
    hh2$DoorSurface[i] <- -9; hh2$DoorWgt[i] <- -9; hh2$Buoyancy[i]<- -9;
    hh2$KiteDim[i] <- -9; hh2$WgtGroundRope[i] <- -9
    # NS-IBTS
  } else if (hh2$survey[i]=='NS-IBTS' & hh2$gearType[i] %in% c("GOV-60","GOV-R-60") &
             hh2$year[i]>=2004 & !is.na(hh2$gearType[i])){
    hh2$Gear[i] <- 'GOV'; hh2$SweepLngt[i] <- 60; hh2$GearExp[i] <-"S";
    hh2$DoorType[i] <- "P"; hh2$Warpdia[i] <- 20; hh2$WarpDen[i] <- 1.5817;
    hh2$DoorSurface[i] <- 4.5; hh2$DoorWgt[i] <- 1250; hh2$Buoyancy[i]<- 172;
    hh2$KiteDim[i] <- 0.7225;hh2$WgtGroundRope[i] <- -9
  } else if (hh2$survey[i]=='NS-IBTS' & hh2$gearType[i] %in% c("GOV-110","GOV-R-110") &
             hh2$year[i]>=2004 & !is.na(hh2$gearType[i])) {
    hh2$Gear[i] <- 'GOV'; hh2$SweepLngt[i] <- 110; hh2$GearExp[i] <-"S";
    hh2$DoorType[i] <- "P"; hh2$Warpdia[i] <- 20; hh2$WarpDen[i] <- 1.5817;
    hh2$DoorSurface[i] <- 4.5; hh2$DoorWgt[i] <- 1250; hh2$Buoyancy[i]<- 172;
    hh2$KiteDim[i] <- 0.7225;hh2$WgtGroundRope[i] <- -9
    # Other
  } else {
    hh2$Gear[i] <- ifelse(!is.na(hh2$gearType[i]),hh2$gearType[i],-9);
    hh2$SweepLngt[i] <- -9; hh2$GearExp[i] <- -9;hh2$DoorType[i] <- -9;
    hh2$Warpdia[i] <- -9; hh2$WarpDen[i] <- -9; hh2$DoorSurface[i] <- -9;
    hh2$DoorWgt[i] <- -9; hh2$Buoyancy[i]<- -9; hh2$KiteDim[i] <- -9;
    hh2$WgtGroundRope[i] <- -9 }
}

```


```{r dataHL, echo=FALSE, include=FALSE, cache=FALSE}

# PREPARE DATA HL AND CA ######################################################

# Attach aphia ID
hlca_2 <- merge(hlca, species[, c("speciesCode", "aphiaID")],all.x = TRUE)
# Marking CatIdentifier, if the species only occur once in the specieslist,
# then CatIdentifier = 1, the the species occurs multiple times  (n) per specieslist
# then CatIdentifier = 1:n
HL_CatId <- unique(hlca_2[, c("sampleId", "speciesCode", "speciesListId")]) %>%
  dplyr::group_by(sampleId, speciesCode) %>%
  dplyr::mutate(CatIdentifier=1:n())

# Merge to hlca
hlca1 <- merge(hlca_2, HL_CatId)


# DATA HL #####################################################################

hl2_0 <- hlca1[!is.na(hlca1$raisingFactor),]

# Define variables
hl2 <- data.frame(hlca1, SpecCodeType = "W", SpecVal = 1, LngtCode = ".",
                  stringsAsFactors = FALSE, subFactor = ifelse_na(hlca1$raisingFactor),
                  SpecCode = ifelse_na(hlca1$aphiaID), Sex = ifelse_na(hlca1$speciesList_sexCode))

# Sub weight as minimum weight step
hl2$subWgt <- as.numeric(apply(hl2[, c("weightStep0", "weightStep1", "weightStep2", "weightStep3")],
                               1, function(x) min(x[1], x[2], x[3], x[4], na.rm = TRUE)*1000))
hl2$subWgt[hl2$subWgt == "Inf"] <- -9


# AGGREGATE DATA HL -----------------------------------------------------------

# Sum animal_number (number in animal table) by grouped variables
hl3 <- sqldf('select   sampleid, specieslistid, SpecCodeType, SpecCode, SpecVal,
             Sex, CatIdentifier, representative, SubFactor, SubWgt,
             LngtCode, length as LngtClass, sum(Animal_number) as HlNoAtLngt
             from     hl2
             group by sampleid, specieslistid, SpecCodeType, SpecCode, SpecVal, Sex,
             CatIdentifier, representative, SubFactor, SubWgt, LngtCode, length')

# Get total weight, CatCatchWgt, by multiplying subfactor and subwgt - per length class
hl4_a <- sqldf('select   sampleid, specieslistid, SpecCodeType, SpecCode, SpecVal, Sex,
               CatIdentifier, representative, SubFactor, SubWgt,LngtCode,
               LngtClass, HlNoAtLngt, SubFactor*SubWgt as CatCatchWgt
               from     hl3
               group by sampleid, specieslistid, SpecCodeType, SpecCode, SpecVal, Sex,
               CatIdentifier, representative,LngtClass
               order by sampleid')

# Get number of length measured fish and total number of caught fish
hl4_b <- sqldf('select   sampleid, specieslistid, SpecCodeType, SpecCode, SpecVal,
               Sex, CatIdentifier, representative, SubFactor, SubWgt,
               sum(HlNoAtLngt) as NoMeas, sum(HlNoAtLngt)*subFactor as TotalNo
               from     hl3
               group by sampleid, specieslistid, SpecCodeType, SpecCode, SpecVal, Sex,
               CatIdentifier, representative
               order by sampleid')

# Must do two steps!! (SAS can do hl4 in one..)
hl4 <- merge(hl4_a, hl4_b, all = TRUE)

# FINAL HL --------------------------------------------------------------------

# Specieslist without length/Nomeas;
if (survey %in% c("BITS","KASU","NS-IBTS") ) {
  hl4[is.na(hl4$LngtClass) & !is.na(hl4$NoMeas), "LngtCode"] <- "-9"
  hl4[is.na(hl4$LngtClass) & !is.na(hl4$NoMeas), "SpecVal"] <- "4"
  hl4[is.na(hl4$LngtClass) & !is.na(hl4$NoMeas), "HlNoAtLngt"] <- -9
  hl4[is.na(hl4$LngtClass) & !is.na(hl4$NoMeas), "LngtClass"] <- -9

  hl5 <- hl4[!(is.na(hl4$LngtClass) & is.na(hl4$NoMeas) ),]

} else if (survey %in% c("TOR","TN","TBM","MS") ) {
  hl4[is.na(hl4$LngtClass),"LngtCode"] <- "-9"
  hl4[is.na(hl4$LngtClass),"SpecVal"] <- "4"
  hl4[is.na(hl4$LngtClass),"HlNoAtLngt"] <- -9
  hl4[is.na(hl4$LngtClass) & is.na(hl4$NoMeas), "TotalNo"] <- -9
  hl4[is.na(hl4$LngtClass) & is.na(hl4$NoMeas), "representative"] <- "ja"
  hl4[is.na(hl4$LngtClass) & is.na(hl4$NoMeas), "NoMeas"] <- -9
  hl4[is.na(hl4$LngtClass), "LngtClass"] <- -9

  hl5 <- hl4
}


# COMBINE DATA HH AND HL ######################################################

hhhl <- merge(hh2, hl5, by = "sampleId", all = TRUE)

# hhhl[hhhl$HaulVal=="I","SpecVal"] <- 0
hhhl$SpecVal[hhhl$HaulVal=="I"] <- 0
hhhl$SpecVal[hhhl$HaulVal=="A"] <- 0


```


```{r dataCA, echo=FALSE, include=FALSE, cache=FALSE}

# DATA CA ###################################################################

# Missign and zero values
if (survey %in%  c("BITS","KASU","NS-IBTS") ) {

  hlca1[is.na(hlca1$HlNoAtLngt) | hlca1$HlNoAtLngt == 0,"HlNoAtLngt"] <- -9
  hlca1[is.na(hlca1$TotalNo) | hlca1$TotalNo == 0,"TotalNo"] <- -9
  hlca1[is.na(hlca1$NoMeas) | hlca1$NoMeas == 0,"NoMeas"] <- -9

  ca_1 <- hlca1[!(hlca1$individNum > 0 & is.na(hlca1$length)
                  & is.na(hlca1$age)),]
  ca <- ca_1[ca_1$individNum>0 & !is.na(ca_1$individNum) |
                !is.na(ca_1$age) ,]
} else {
  ca <- hlca1[hlca1$individNum>0 & !is.na(hlca1$individNum) |
                !is.na(hlca1$age),]
}

# Age -------------------------------------------------------------------------
ca[is.na(ca$Age_Number) & is.na(ca$age),"Age_Number"] <-
  ca[is.na(ca$age) & is.na(ca$Age_Number),"Animal_number"]
ca$age[is.na(ca$age)] <- -9

# Sex -------------------------------------------------------------------------
ca[!is.na(ca$sexCode),"Sex_CA"] <- ca[!is.na(ca$sexCode),"sexCode"]
ca[is.na(ca$sexCode),"Sex_CA"] <- ca[is.na(ca$sexCode),"speciesList_sexCode"]
ca$Sex_CA[is.na(ca$Sex_CA) | ca$Sex_CA=="T"] <- "-9"

# Various variables -----------------------------------------------------------

if (nrow(ca)>0){
ca$SpecCodeType <- "W"
ca$SpecCode <- ca$aphiaID
ca$SpecVal = 1
ca$LngtCode = "."
ca$PlusGr = '-9'

# Maturity --------------------------------------------------------------------

# No Maturity
ca[!(ca$maturityIndexMethod %in% c("A","B","C","I","M")) |
     is.na(ca$maturityIndex),"Maturity"] <- "-9"

ca[is.na(ca$maturityIndexMethod),"maturityIndexMethod"] <- "-9"

# Method A
ca[ca$maturityIndexMethod == 'A' & ca$maturityIndex == 1, "Maturity"] <- 61
ca[ca$maturityIndexMethod == 'A' & ca$maturityIndex %in% c(2:5), "Maturity"] <- 62
ca[ca$maturityIndexMethod == 'A' & ca$maturityIndex == 6, "Maturity"] <- 63
ca[ca$maturityIndexMethod == 'A' & ca$maturityIndex == 7, "Maturity"] <- 64
ca[ca$maturityIndexMethod == 'A' & ca$maturityIndex == 8, "Maturity"] <- 66

# Method B
ca[ca$maturityIndexMethod == 'B', "Maturity"] <-
  60 + ca[ca$maturityIndexMethod == 'B',]$maturityIndex

# Method C
ca[ca$maturityIndexMethod == 'C' & ca$maturityIndex %in% c(1:2), "Maturity"] <- 61
ca[ca$maturityIndexMethod == 'C' & ca$maturityIndex %in% c(3:4), "Maturity"] <- 62
ca[ca$maturityIndexMethod == 'C' & ca$maturityIndex %in% c(5:7), "Maturity"] <- 63
ca[ca$maturityIndexMethod == 'C' & ca$maturityIndex == 8, "Maturity"] <- 64
ca[ca$maturityIndexMethod == 'C' & ca$maturityIndex == 9, "Maturity"] <- 65
ca[ca$maturityIndexMethod == 'C' & ca$maturityIndex == 10, "Maturity"] <- 66

# Method I
ca[ca$maturityIndexMethod == 'I', "Maturity"] <-
  60 + ca[ca$maturityIndexMethod == 'I',]$maturityIndex

# Method M
ca[ca$maturityIndexMethod == 'M' & ca$maturityIndex == 1, "Maturity"] <- 61
ca[ca$maturityIndexMethod == 'M' & ca$maturityIndex %in% c(2:3), "Maturity"] <- 62
ca[ca$maturityIndexMethod == 'M' & ca$maturityIndex == 4, "Maturity"] <- 63
ca[ca$maturityIndexMethod == 'M' & ca$maturityIndex == 5, "Maturity"] <- 64
ca[ca$maturityIndexMethod == 'M' & ca$maturityIndex == 6, "Maturity"] <- 65

} else{
  ca <- cbind(ca,data.frame(SpecCodeType=character(),
                          SpecCode=integer(),
                          SpecVal = integer(),
                          LngtCode = character(),
                          PlusGr = character(),
                          Maturity = integer(),
                          stringsAsFactors = F))
}
# AGGREGATING BIOLOGICAL DATA #################################################

# representative out???

# Sum number of aged fish per length class
ca_age <- sqldf('select   sampleId, speciesListId, SpecCodeType, SpecCode,
                          SpecVal, Sex_CA, CatIdentifier, LngtCode, 
                          length as LngtClass, PlusGr, age as AgeRings, 
                          Maturity, sum(age_number) as CANoAtLngt, representative
                 from     ca
                 group by sampleId, speciesListId, SpecCodeType, SpecCode, SpecVal, 
                          Sex_CA, CatIdentifier, representative,
                          LngtCode, LngtClass, PlusGr, age, Maturity')
# LngtCode, length, PlusGr, age, Maturity')

# sum total number of fish and weight per length
ca_wgt <- sqldf('select   sampleId, speciesListId, SpecCodeType, SpecCode, SpecVal, 
                          Sex_CA, CatIdentifier, LngtCode, length as LngtClass,
                          PlusGr, age as AgeRings, Maturity, representative,
                          sum(weight*1000)/sum(Animal_number) as IndWgt
                 from     ca
                 where    weight not like "NA"
                 group by sampleId, speciesListId, SpecCodeType, SpecCode, SpecVal, 
                          Sex_CA, CatIdentifier, LngtCode, representative,
                          length, PlusGr,age, Maturity')


ca3 <- merge(ca_age, ca_wgt, by = c("sampleId", "speciesListId","representative",
                                    "SpecCodeType", "SpecCode", "SpecVal", "Sex_CA",
                                    "CatIdentifier", "LngtCode", "LngtClass",
                                    "PlusGr", "AgeRings", "Maturity"), all = TRUE)



if (nrow(ca3)>0){
  ca3$CAMark <- 1
} else{
  ca3 <- cbind(ca3,data.frame(CAMark=integer()))
  }

ca3 <- ca3[!is.na(ca3$LngtClass),]

# Merge with haul value to identify "invalid catch"
ca4 <- merge(ca3, unique(hhhl[,c("HaulVal", "sampleId")]) )

if (nrow(ca4)>0){
  ca4[ca4$HaulVal == "I", "SpecVal"] <- 0
}

# COMBINE DATA HH, HL AND CA ##################################################


if (nrow(ca)>0) {
  hhhlca <- merge(hhhl, ca4, all = TRUE)
} else {
  hhhlca <- hhhl
}



```

```{r non_rep_data, echo=FALSE, include=FALSE, cache=FALSE}

# NON REP DATA ################################################################

#Non representative data (EjRep)
rep <- sqldf('select distinct  sampleid, specieslistid, representative
             from             hhhlca
             order by         sampleid, specieslistid, representative')

# If first occurence of speciesListID then rep=1
# rep[c(1, 1 + which(diff(rep$speciesListId) != 0)), "rep"] <- 1

rep <- rep %>% 
  dplyr::group_by(sampleId,speciesListId) %>% 
  dplyr::mutate(rep = ifelse(row_number()==1,1,NA)) %>% 
  data.frame()

rep2 <- rep[!is.na(rep$rep) & rep$representative == "nej" &
              !is.na(rep$representative),]

# MERGE NON REP DATA ----------------------------------------------------------

hhhlca2 <- merge(hhhlca, rep2, all = TRUE)

hhhlca3_1 <- data.frame(hhhlca2, "Length_HL" = hhhlca2$LngtClass,
                        "LngtCode_HL" = hhhlca2$LngtCode,"ageRecord" = 0,
                        stringsAsFactors = FALSE)

# DATA EJREP ----
in_ejRep <- which(hhhlca3_1$rep == 1 & !is.na(hhhlca3_1$rep))

#hhhlca3_1[in_ejRep, "DataType"] <- '-9'
hhhlca3_1[in_ejRep, "representative"] <- 'ja'
hhhlca3_1[in_ejRep, "SpecVal"] <- 0
hhhlca3_1[in_ejRep, "Sex"] <- '-9'
hhhlca3_1[in_ejRep, "TotalNo"] <- -9
hhhlca3_1[in_ejRep, "CatIdentifier"] <- -9
hhhlca3_1[in_ejRep, "NoMeas"] <- -9
hhhlca3_1[in_ejRep, "subFactor"] <- -9
hhhlca3_1[in_ejRep, "subWgt"] <- -9
hhhlca3_1[in_ejRep, "CatCatchWgt"] <- -9
hhhlca3_1[in_ejRep, "LngtCode_HL"] <- -9
hhhlca3_1[in_ejRep, "Length_HL"] <- -9
hhhlca3_1[in_ejRep, "HlNoAtLngt"] <- -9

```

```{r final_data, echo=FALSE, include=FALSE, cache=FALSE}

# MAKING FINAL DATA SET  ######################################################

#Final corrections
hhhlca3_2 <- hhhlca3_1[!(hhhlca3_1$year == 2010 & hhhlca3_1$cruise == "KASU-2" &
                           hhhlca3_1$station %in% c(2975,2976) & hhhlca3_1$SpecCode == 126444),]
hhhlca3_3 <- hhhlca3_2[!(hhhlca3_2$year == 2010 & hhhlca3_2$cruise == "BITS-1" &
                           hhhlca3_2$station == 231 & hhhlca3_2$SpecCode == 126425),]


if (nrow(ca)>0) {
  #Make data with CA mark = 1  (CA data lines)
  hhhlca3_4 <- hhhlca3_3[hhhlca3_3$LngtClass != 0 | is.na(hhhlca3_3$LngtClass),]
  hhhlca3_4$ageRecord <- 0

  hhhlca3_4par <- hhhlca3_4[hhhlca3_4$CAMark == 1 & !is.na(hhhlca3_4$CAMark),]
  hhhlca3_4par$ageRecord <- 1
  #Final Data
  hhhlca3 <- rbind(hhhlca3_4, hhhlca3_4par)

} else {
  #Final Data
  hhhlca3 <- hhhlca3_3
}


# if (survey == "TBM") { hhhlca3$StNo = hhhlca3$stationName}
if (survey == "TBM") { hhhlca3$StNo = gsub(as.character(hhhlca3$stationName),
                                           pattern = "[^[:alnum:]]",
                                           replacement = "_")}
```

## DATRAS

```{r OutputAndFiles, echo=FALSE, include=FALSE, cache=FALSE}

# INDICES FOR SELECTING DATA FOR EACH DATA TYPE ###############################

hhhlca3 <- hhhlca3[with(hhhlca3, order(StNo, sampleId, speciesListId,
                                       ageRecord, Length_HL)), ]

# Indices to use in HH --------------------------------------------------------

# Remove duplicates and keep first occurence of sampleId
in_HH <- seq_along(hhhlca3$sampleId)[!duplicated(hhhlca3$sampleId)]

# Indices to use in HL --------------------------------------------------------

# First occurence of unique variables: stNo, sampleId, specieslistId...
first_HL <- !duplicated(hhhlca3[,c("StNo", "sampleId", "speciesListId",
                                   "ageRecord", "Length_HL")])
in_HL1 <- seq_along(hhhlca3$Length_HL)[first_HL]
hhhlca3[in_HL1, "tjek"] <- 1

hhhlca3$haul.id <- paste(hhhlca3$year, hhhlca3$quarterGearStart, hhhlca3$country, hhhlca3$platform1, hhhlca3$Gear, hhhlca3$StNo, hhhlca3$HaulNo, sep = ":")

# Keep if tjek = 1 and agerecord = 0
in_HL <- which(hhhlca3$tjek == 1 & !is.na(hhhlca3$SpecCode) &
                 hhhlca3$ageRecord == 0 & hhhlca3$representative == "ja" )

# Indices to use in CA --------------------------------------------------------

# Keep all records where ageRecord=1
if (nrow(ca)>0) {
  in_CA <- which(hhhlca3$ageRecord==1)
} else  {
  in_CA <- 1
}


# MAKE DATA FILES: HH, HL, CA #################################################

# Corerct missing values
#hhhlca3[is.na(hhhlca3)] <- -9

# HH
DATA_HH <- data.frame(
  "RecordType" = "HH", "Survey" = hhhlca3$survey[in_HH],
  "Quarter" = hhhlca3$quarterGearStart[in_HH], "Country" = hhhlca3$country[in_HH],
  "Ship" = hhhlca3$ship[in_HH], "Gear" = hhhlca3$Gear[in_HH],
  "SweepLngt" = hhhlca3$SweepLngt[in_HH], "GearExp" = hhhlca3$GearExp[in_HH],
  "DoorType" = hhhlca3$DoorType[in_HH], "StNo" = hhhlca3$StNo[in_HH],
  "HaulNo" = hhhlca3$HaulNo[in_HH], "Year" = hhhlca3$year[in_HH],
  "Month" = hhhlca3$month[in_HH], "Day" = hhhlca3$day[in_HH],
  "TimeShot" = hhhlca3$TimeShot[in_HH], "Stratum" = hhhlca3$stratum[in_HH],
  "HaulDur" = hhhlca3$HaulDur[in_HH],"DayNight" = hhhlca3$DayNight[in_HH],
  "ShootLat" = hhhlca3$ShootLat[in_HH], "ShootLong" = hhhlca3$ShootLong[in_HH],
  "HaulLat" = hhhlca3$HaulLat[in_HH], "HaulLong" = hhhlca3$HaulLong[in_HH],
  "StatRec" = hhhlca3$StatRec[in_HH], "Depth" = hhhlca3$Depth[in_HH],
  "HaulVal" = hhhlca3$HaulVal[in_HH], "HydroStNo" = hhhlca3$HydroStNo[in_HH],
  "StdSpecRecCode" = hhhlca3$StdSpecRecCode[in_HH],
  "BycSpecRecCode" = hhhlca3$BycSpecRecCode[in_HH],
  "DataType" = hhhlca3$DataType[in_HH], "Netopening" = hhhlca3$netOpening[in_HH],
  "Rigging" = hhhlca3$Rigging[in_HH], "Tickler" = hhhlca3$Tickler[in_HH],
  "Distance" = hhhlca3$Distance[in_HH], "Warplngt" = hhhlca3$WarpLngt[in_HH],
  "Warpdia" = hhhlca3$Warpdia[in_HH], "WarpDen"=hhhlca3$WarpDen[in_HH],
  "DoorSurface" = hhhlca3$DoorSurface[in_HH], "DoorWgt"=hhhlca3$DoorWgt[in_HH],
  "DoorSpread" = hhhlca3$DoorSpread[in_HH], "WingSpread"=hhhlca3$wingSpread[in_HH],
  "Buoyancy" = hhhlca3$Buoyancy[in_HH], "KiteDim" = hhhlca3$KiteDim[in_HH],
  "WgtGroundRope" = hhhlca3$WgtGroundRope[in_HH], "TowDir" = hhhlca3$TowDir[in_HH],
  "GroundSpeed" = hhhlca3$GroundSpeed[in_HH],"SpeedWater" = hhhlca3$SpeedWater[in_HH],
  "SurCurDir" = hhhlca3$SurCurDir[in_HH], "SurCurSpeed" = hhhlca3$SurCurSpeed[in_HH],
  "BotCurDir" = hhhlca3$BotCurDir[in_HH], "BotCurSpeed" = hhhlca3$BotCurSpeed[in_HH],
  "WindDir" = hhhlca3$WindDir[in_HH], "WindSpeed"=hhhlca3$windSpeed[in_HH],
  "SwellDir"= hhhlca3$SwellDir[in_HH], "SwellHeight" = hhhlca3$SwellHeight[in_HH],
  "SurTemp" = hhhlca3$SurTemp[in_HH], "BotTemp" = hhhlca3$BotTemp[in_HH],
  "SurSal"=hhhlca3$SurSal[in_HH], "BotSal" = hhhlca3$BotSal[in_HH],
  "ThermoCline" = hhhlca3$thermoCline[in_HH], "ThClineDepth" = hhhlca3$ThClineDepth[in_HH],
  "DateofCalculation" = format(Sys.Date(),"%Y%m%d"),
  stringsAsFactors = FALSE)

# CA
if (nrow(ca)>1) {
  DATA_CA <- data.frame(
    "RecordType" = "CA", "Survey" = hhhlca3$survey[in_CA],
    "Quarter" = hhhlca3$quarterGearStart[in_CA], "Country" = hhhlca3$country[in_CA],
    "Ship" = hhhlca3$ship[in_CA], "Gear" = hhhlca3$Gear[in_CA],
    "SweepLngt" = hhhlca3$SweepLngt[in_CA],"GearExp" = hhhlca3$GearExp[in_CA],
    "DoorType" = hhhlca3$DoorType[in_CA], "StNo" = hhhlca3$StNo[in_CA],
    "HaulNo" = hhhlca3$HaulNo[in_CA], "Year" = hhhlca3$year[in_CA],
    "SpecCodeType" = hhhlca3$SpecCodeType[in_CA], "SpecCode" = hhhlca3$SpecCode[in_CA],
    "AreaType" = 0, "AreaCode" = hhhlca3$StatRec[in_CA],
    "LngtCode" = hhhlca3$LngtCode[in_CA], "LngtClass" = hhhlca3$LngtClass[in_CA],
    "Sex" = hhhlca3$Sex_CA[in_CA], "Maturity" = hhhlca3$Maturity[in_CA],
    "PlusGr" = hhhlca3$PlusGr[in_CA], "AgeRings" = hhhlca3$AgeRings[in_CA],
    "CANoAtLngt" = hhhlca3$CANoAtLngt[in_CA],
    "IndWgt" = hhhlca3$IndWgt[in_CA], "DateofCalculation" = format(Sys.Date(),"%Y%m%d"),
    "ValidAphiaID" = hhhlca3$SpecCode[in_CA],
    stringsAsFactors = FALSE)
} else {
  DATA_CA <- data.frame("RecordType"="CA","Survey"=-9,"Quarter"=-9,
                        "Country"=-9,"Ship"=-9,"Gear"=-9,"SweepLngt"=-9,"GearExp"=-9,
                        "DoorType"=-9,"StNo"=-9, "HaulNo"=-9,"Year"=-9,"SpecCodeType"=-9,
                        "SpecCode"=-9,"AreaType"=-9,"AreaCode"=-9,"LngtCode"=-9,
                        "LngtClass"=-9, "Sex"=-9,"Maturity"=-9, "PlusGr"=-9,"AgeRings"=-9,"CANoAtLngt"=-9,
                        "IndWgt"=-9,"DateofCalculation"=format(Sys.Date(),"%Y%m%d"),
                        "ValidAphiaID"=-9,stringsAsFactors = FALSE)
}

# HL
DATA_HL <- data.frame(
  "RecordType" = "HL", "Survey" = hhhlca3$survey[in_HL],
  "Quarter" = hhhlca3$quarterGearStart[in_HL], "Country" = hhhlca3$country[in_HL],
  "Ship" = hhhlca3$ship[in_HL], "Gear" = hhhlca3$Gear[in_HL],
  "SweepLngt" = hhhlca3$SweepLngt[in_HL], "GearExp" = hhhlca3$GearExp[in_HL],
  "DoorType" = hhhlca3$DoorType[in_HL], "StNo" = hhhlca3$StNo[in_HL],
  "HaulNo" = hhhlca3$HaulNo[in_HL], "Year" = hhhlca3$year[in_HL],
  "SpecCodeType" = hhhlca3$SpecCodeType[in_HL], "SpecCode" = hhhlca3$SpecCode[in_HL],
  "SpecVal" = hhhlca3$SpecVal[in_HL], "Sex" = hhhlca3$Sex[in_HL],
  "TotalNo" = hhhlca3$TotalNo[in_HL], "CatIdentifier" = hhhlca3$CatIdentifier[in_HL],
  "NoMeas" = hhhlca3$NoMeas[in_HL], "SubFactor" = hhhlca3$subFactor[in_HL],
  "SubWgt" = hhhlca3$subWgt[in_HL], "CatCatchWgt" = hhhlca3$CatCatchWgt[in_HL],
  "LngtCode" = hhhlca3$LngtCode[in_HL], "LngtClass" = hhhlca3$Length_HL[in_HL],
  "HLNoAtLngt" = hhhlca3$HlNoAtLngt[in_HL], "DateofCalculation"=format(Sys.Date(),"%Y%m%d"),
  "ValidAphiaID" = hhhlca3$SpecCode[in_HL],
  stringsAsFactors = FALSE)


DATA_HH[is.na(DATA_HH) | DATA_HH == ""] <- "-9"
DATA_HL[is.na(DATA_HL) | DATA_HL == ""] <- "-9"
DATA_CA[is.na(DATA_CA) | DATA_CA == ""] <- "-9"



DATA_HH <- DATA_HH[order(as.integer(DATA_HH$Year), as.integer(DATA_HH$Quarter),
                         as.integer(DATA_HH$HaulNo)),]
DATA_HL <- DATA_HL[order(as.integer(DATA_HL$Year), as.integer(DATA_HL$Quarter),
                         as.integer(DATA_HL$HaulNo)),]
DATA_CA <- DATA_CA[order(as.integer(DATA_CA$Year), as.integer(DATA_CA$Quarter),
                         as.integer(DATA_CA$HaulNo)),]



# If selected species only
if (length(art_out) != 0) {

  art_code <- species[species$speciesCode %in% art_out,"aphiaID"]

  DATA_HL <- DATA_HL[DATA_HL$SpecCode %in% art_code,]
  DATA_CA <- DATA_CA[DATA_CA$SpecCode %in% art_code,]

}

recordtypes <- c("HH","HL","CA")
notTheseCols <- c("Survey","DateofCalculation","ValidAphiaID")
data_hh2 <- data.frame(station = DATA_HH$StNo,
                       recordtype = DATA_HH$RecordType,
                       string = capture.output(
                         write.table(DATA_HH[,!colnames(DATA_HH) %in% notTheseCols],
                                     sep=",", row.names = FALSE, quote=FALSE, 
                                     col.names = FALSE)))
data_hl2 <- data.frame(station = DATA_HL$StNo,
                       recordtype = DATA_HL$RecordType,
                       string = capture.output(
                         write.table(DATA_HL[,!colnames(DATA_HL) %in% notTheseCols],
                                     sep=",", row.names = FALSE, quote=FALSE,
                                     col.names = FALSE)))
data_ca2 <- data.frame(station = DATA_CA$StNo,
                       recordtype = DATA_CA$RecordType,
                       string = capture.output(
                         write.table(DATA_CA[,!colnames(DATA_CA) %in% notTheseCols], 
                                     sep=",", row.names = FALSE, quote=FALSE,
                                     col.names = FALSE)))

DATA_ALL <- merge(merge(data_hh2, data_hl2, all = TRUE),data_ca2, all=TRUE)
DATA_ALL$recordtype <- factor(DATA_ALL$recordtype, levels=recordtypes )
DATA_ALL <- DATA_ALL[order(DATA_ALL$station, DATA_ALL$recordtype),]


data_out <- DATA_ALL$string
```

#TEST



```{r output, include=FALSE}
#OUTPUT DATA #################################################################

#path <- "C:\\Users\\lipi\\Documents\\"
path <- ""
V_years <- ifelse(length(v_year) > 1, 
                  paste(min(v_year), max(v_year),sep = '-'),
                  v_year)
V_today <- format(Sys.Date(),"%d%m%y")


# Indivudal HH, HL and CA files -----------------------------------------------

write.csv(DATA_HH, file = paste(path,"HH_",cruise_all,"_",V_years,"_",V_today,".csv", sep=""),
          row.names=FALSE,quote = FALSE)
write.csv(DATA_HL, file = paste(path,"HL_",cruise_all,"_",V_years,"_",V_today,".csv", sep=""),
          row.names=FALSE,quote = FALSE)
write.csv(DATA_CA, file = paste(path,"CA_",cruise_all,"_",V_years,"_",V_today,".csv", sep=""),
          row.names=FALSE,quote = FALSE)

# Combined data ---------------------------------------------------------------

write.table(DATA_HH,file=paste0(path,"ALL_",cruise_all,"_",V_years,"_",V_today,".csv"), sep=",",
            row.names = FALSE, quote=FALSE)
write.table(DATA_HL,file=paste0(path,"ALL_",cruise_all,"_",V_years,"_",V_today,".csv"), sep=",",
            row.names = FALSE, quote=FALSE, append=TRUE)
write.table(DATA_CA,file=paste0(path,"ALL_",cruise_all,"_",V_years,"_",V_today,".csv"), sep=",",
            row.names = FALSE, quote=FALSE, append=TRUE)

#utils::zip(files = paste0(path,"ALL_",cruise_all,"_",V_years,"_",V_today,".csv"),
#           zipfile = paste0(path,"ALL_",cruise_all,"_",V_years,"_",V_today,".zip"))

# Upload format to ICES -------------------------------------------------------
# No headers
fileConn <- file(sprintf("%sUpload_ALL_%s_%s_%s.csv",path,cruise_all,V_years,V_today))
# write.table(data_out, file=paste0(path,"Upload_ALL_",cruise_all,"_",V_years,"_",V_today,".csv"),
#             sep=",", row.names = FALSE, quote=FALSE, col.names = FALSE)
writeLines(text = as.vector(data_out),con = fileConn)
close(fileConn)
```
