
---
fontsize: 12pt
geometry: margin=0.6in
header-includes:
- \usepackage{tabularx}
- \usepackage{longtable}
- \usepackage[table]{}
- \usepackage[danish]{babel}
output: pdf_document
classoption: x11names
---

\renewcommand{\familydefault}{\sfdefault}
\sffamily


```{r set_libraries, include=FALSE}
if (!require("pacman")) install.packages("pacman")
p_load(sqldf, RODBC, lubridate, data.table, kableExtra, plyr)

```



```{r selcectData, echo=FALSE,include=FALSE}
year_in <- 2023
cruise_in <- c("MON", "SEAS")

year_in <- @paramYear
cruise_in <- @paramCruise

channel <- odbcConnect("FishLineDW")
trips <- sqlQuery(channel, paste("SELECT     year as Aar, cruise as Togt, trip, platform1 as Kutter, 
dateStart, dateEnd,  
{ fn QUARTER(dateStart) } AS Kvartal, 1 as t
                                  FROM       fishlineDW.dbo.Trip
                                  WHERE     (cruise IN ('", paste(cruise_in,collapse = "','"),"'))  AND
                                            (year = ",year_in,") " 
                                , sep = ""))
close(channel)

```

```{r countTrips, include=FALSE}
trips$dateStart <- force_tz(trips$dateStart, tzone = "UTC")
trips$dateEnd <- force_tz(trips$dateEnd, tzone = "UTC")

trips$n_days <- as.numeric(difftime(trips$dateEnd, trips$dateStart, units = "days"))
trips$Togt <- toString(cruise_in)

setDT(trips)

#pr kutter, kvartal
q_kut <- trips[ ,. (n_tur = sum(t),
                    n_day = sum(n_days)),
                by = .(Aar, Togt, Kvartal, Kutter)] 
q_kut <- q_kut[order(q_kut$Kvartal, q_kut$Kutter), ]


# pr kutter
kut <- trips[ ,. (n_tur = sum(t),
                    n_day = sum(n_days)),
                by = .(Aar, Togt, Kutter)] 
kut <- kut[order(kut$Kutter), ]

#pr kvartal
q <- trips[ ,. (n_tur = sum(t),
                    n_day = sum(n_days)),
                by = .(Aar, Togt, Kvartal)] 
q <- q[order(q$Kvartal), ]

q <- rbind.fill(q, data.frame(n_tur = sum(q$n_tur), n_day = sum(q$n_day)))
q[is.na(q)] <- ""

#wite out csv
write.csv(kut, file=paste0("turePerKutter_",cruise_in,year_in,".csv"),row.names=FALSE)
write.csv(q_kut ,file=paste0("turePerKutterKvartal_",cruise_in,year_in,".csv"),row.names=FALSE)
write.csv(q ,file=paste0("AntalTure_",cruise_in,year_in,".csv"),row.names=FALSE)

```

\section{Antal discardture pr. år, kvartal og kutter}
\vspace{-0.5cm}

Udskrevet `r format(Sys.Date(), "%d-%m-%Y")`
\vspace{0.5cm}

\def\arraystretch{1.3}

```{r numberTrips, results='asis',echo=FALSE,message=FALSE,warning=FALSE}

cat(paste0("\\subsubsection*{Antal ",cruise_in,"-ture i ",year_in,"}")) 
cat("\\vspace{0.3cm}")
#########################################################################

q$n_day <- signif(q$n_day, 2)
q <- cbind("", q)

q %>%
     kbl(escape = F, longtable = T, booktabs = T, linesep = "", row.names = F,
         col.names = c("", "År", "Togt", "Kvartal", "Antal Ture", "Antal Dage"), 
         align = "l") %>%
         row_spec(0, bold = FALSE) %>%
         kable_styling(latex_options = c("striped", "hold_position")) %>%
         column_spec(1:5, width = "4cm") %>%
         pack_rows("Total", 5, 5, latex_gap_space = "2em") 
 
```

\newpage

```{r tripsYear, results='asis',echo=FALSE,message=FALSE,warning=FALSE,position='left'}
cat(paste0("\\subsubsection*{Antal ",cruise_in,"-ture pr. fartøj i ",year_in,"}")) 
cat("\\vspace{0.3cm}")

kut$n_day <- signif(kut$n_day, 2)

kut %>%
    kbl(escape = F, longtable = T, booktabs = T, linesep = "", row.names = F,
         col.names = c("År", "Togt", "Kutter", "Antal Ture", "Antal Dage"), 
         align = "l") %>%
         row_spec(0, bold = FALSE) %>%
         kable_styling(latex_options = c("striped", "hold_position")) %>%
         column_spec(1:5, width = "4cm") 


```

\newpage

```{r tripsQuarter, results='asis',echo=FALSE,message=FALSE,warning=FALSE,position='left'}

cat(paste0("\\subsubsection*{Antal ",cruise_in,"-ture pr. fartøj i ",i,". kvartal ",year_in,"}"))
    cat("\\vspace{0.3cm}")
  
q_kut$n_day <- signif(q_kut$n_day, 2)

ind1 <- range(which(q_kut$Kvartal == 1))
ind2 <- range(which(q_kut$Kvartal == 2))
ind3 <- range(which(q_kut$Kvartal == 3))
ind4 <- range(which(q_kut$Kvartal == 4))

q_kut[, "Kvartal"] <- NULL
q_kut <- cbind("", q_kut)

q_kut %>%
     kbl(escape = F, longtable = T, booktabs = T, linesep = "", row.names = F,
         col.names = c("", "År", "Togt", "Kutter", "Antal Ture", "Antal Dage"), 
         align = "l") %>%
         row_spec(0, bold = FALSE) %>%
         kable_styling(latex_options = c("striped", "hold_position")) %>%
         column_spec(1:5, width = "4cm") %>%
         pack_rows("Kvartal 1", ind1[1], ind1[2], latex_gap_space = "2em") %>%
         pack_rows("Kvartal 2", ind2[1], ind2[2], latex_gap_space = "2em") %>%
         pack_rows("Kvartal 3", ind3[1], ind3[2], latex_gap_space = "2em") %>%
         pack_rows("Kvartal 4", ind4[1], ind4[2], latex_gap_space = "2em")

```
