---
title: "biomass_testing_results"
author: "Kirsten Birch Håkansson, DTU Aqua"
date: \today
output: pdf_document
params:
  species: BMS
  old: v1
  date_old: 23Jan2020
  new: v2
  date_new: 23Jan2020
---

```{r setup, include = F}
options(scipen = 999)

library(dplyr)
library(haven)
library(tidyr)

dir_in <- "Q:/mynd/kibi/fishLine/FishLineRapporter/Biomasseberegninger/creating_a_new_biomasse_report/output/"
dir_out <- "Q:/mynd/kibi/fishLine/FishLineRapporter/Biomasseberegninger/creating_a_new_biomasse_report/testing/"

species <- params$species
v_old <- params$old
date_old <- params$date_old
v_new <- params$new
date_new <- params$date_new
```


```{r get_data, include = F}

old <- readRDS(paste0(dir_in, "Biomasse_", species, "_", v_old, "_", date_old, ".rds"))
new <- readRDS(paste0(dir_in, "Biomasse_", species, "_", v_new, "_", date_new, ".rds"))

#Rename certain columns in new to make comparison
colnames(new)[c(19, 20, 23:ncol(new))] <- paste("New", colnames(new)[c(19, 20, 23:ncol(new))], sep = "_")

# Join by as much as possible
comp <- as.data.frame(full_join(old, new))

# Replave infinet values with 0

comp[comp == "Inf"] <- 0
```

```{r test, include = F}

#==================================================================
# Direct comparison

comp_red <- comp[c(1,3:8,19:60)]

comp_red$diff_RedskabDim <- comp_red$RedskabDim-comp_red$New_RedskabDim
comp_red$diff_Befisket_Areal_m2 <- comp_red$Befisket_Areal_m2-comp_red$New_Befisket_Areal_m2

comp_red$diff_TotalWeight_kg_SMÅ <- comp_red$TotalWeight_kg_SMÅ-comp_red$New_TotalWeight_kg_SMÅ
comp_red$diff_TotalNumber_SMÅ <- comp_red$TotalNumber_SMÅ-comp_red$New_TotalNumber_SMÅ
comp_red$diff_MeanLength_cm_SMÅ <- comp_red$MeanLength_cm_SMÅ-comp_red$New_MeanLength_cm_SMÅ
comp_red$diff_Min_Length_cm_SMÅ <- comp_red$Min_Length_cm_SMÅ-comp_red$New_Min_Length_cm_SMÅ

comp_red$diff_TotalWeight_kg_STO <- comp_red$TotalWeight_kg_STO-comp_red$New_TotalWeight_kg_STO
comp_red$diff_TotalNumber_STO <- comp_red$TotalNumber_STO-comp_red$New_TotalNumber_STO
comp_red$diff_MeanLength_cm_STO <- comp_red$MeanLength_cm_STO-comp_red$New_MeanLength_cm_STO
comp_red$diff_Min_Length_cm_STO <- comp_red$Min_Length_cm_STO-comp_red$New_Min_Length_cm_STO

comp_red$diff_TotalWeight_kg <- comp_red$TotalWeight_kg-comp_red$New_TotalWeight_kg
comp_red$diff_TotalNumber <- comp_red$TotalNumber-comp_red$New_TotalNumber
comp_red$diff_MeanLength_cm <- comp_red$MeanLength_cm-comp_red$New_MeanLength_cm
comp_red$diff_Min_Length_cm <- comp_red$Min_Length_cm-comp_red$New_Min_Length_cm

comp_red$diff_Fangst_kg_m2_SMÅ <- comp_red$Fangst_kg_m2_SMÅ-comp_red$New_Fangst_kg_m2_SMÅ
comp_red$diff_Fangst_kg_m2_STO <- comp_red$Fangst_kg_m2_STO-comp_red$New_Fangst_kg_m2_STO
comp_red$diff_Fangst_kg_m2 <- comp_red$Fangst_kg_m2-comp_red$New_Fangst_kg_m2

comp_red$diff_fangst_oes_kg_m2_SMÅ <- comp_red$fangst_oes_kg_m2_SMÅ-comp_red$New_fangst_oes_kg_m2_SMÅ
comp_red$diff_fangst_oes_kg_m2_STO <- comp_red$fangst_oes_kg_m2_STO-comp_red$New_fangst_oes_kg_m2_STO
comp_red$diff_fangst_oes_kg_m2 <- comp_red$fangst_oes_kg_m2-comp_red$New_fangst_oes_kg_m2
comp_red$diff_Korrigeret_oes_kg_m2_STO <- comp_red$Korrigeret_oes_kg_m2_STO-comp_red$New_Korrigeret_oes_kg_m2_STO
comp_red$diff_Korrigeret_oes_kg_m2 <- comp_red$Korrigeret_oes_kg_m2-comp_red$New_Korrigeret_oes_kg_m2
comp_red$diff_Korrigeret_oes_kg_m2_SMÅ <- comp_red$Korrigeret_oes_kg_m2_STO-comp_red$New_Korrigeret_oes_kg_m2_SMÅ



#Subset for which ones got FALSE

Issue <- subset(comp_red, 
                diff_RedskabDim != 0 |
                diff_Befisket_Areal_m2 != 0 |
                diff_TotalWeight_kg_SMÅ != 0 |
                diff_TotalNumber_SMÅ != 0 | 
                diff_MeanLength_cm_SMÅ != 0 |
                diff_Min_Length_cm_SMÅ != 0 | 
                diff_TotalWeight_kg_STO != 0 |
                diff_TotalNumber_STO != 0 | 
                diff_MeanLength_cm_STO != 0 |
                diff_Min_Length_cm_STO != 0 | 
                diff_TotalWeight_kg != 0 |
                diff_TotalNumber != 0 | 
                diff_MeanLength_cm != 0 |
                diff_Min_Length_cm != 0 | 
                diff_Fangst_kg_m2_SMÅ != 0 |
                diff_Fangst_kg_m2_STO != 0 | 
                diff_Fangst_kg_m2 != 0)

Issue_2 <- subset(comp_red, 
                  diff_RedskabDim != 0 | is.na(diff_RedskabDim) |
                  diff_Befisket_Areal_m2 != 0 | is.na(diff_Befisket_Areal_m2) |
                  diff_TotalWeight_kg_SMÅ != 0 | is.na(diff_TotalWeight_kg_SMÅ) |
                  diff_TotalNumber_SMÅ != 0 | is.na(diff_TotalNumber_SMÅ)  | 
                  diff_MeanLength_cm_SMÅ != 0 | is.na(diff_MeanLength_cm_SMÅ)  |
                  diff_Min_Length_cm_SMÅ != 0 | is.na(diff_Min_Length_cm_SMÅ)  | 
                  diff_TotalWeight_kg_STO != 0 | is.na(diff_TotalWeight_kg_STO)  |
                  diff_TotalNumber_STO != 0 | is.na(diff_TotalNumber_STO)  | 
                  diff_MeanLength_cm_STO != 0 | is.na(diff_MeanLength_cm_STO)  |
                  diff_Min_Length_cm_STO != 0 | is.na(diff_Min_Length_cm_STO)  | 
                  diff_TotalWeight_kg != 0 | is.na(diff_TotalWeight_kg)  |
                  diff_TotalNumber != 0 | is.na(diff_TotalNumber)  | 
                  diff_MeanLength_cm != 0 | is.na(diff_MeanLength_cm)  |
                  diff_Min_Length_cm != 0 | is.na(diff_Min_Length_cm)  | 
                  diff_Fangst_kg_m2_SMÅ != 0 | is.na(diff_Fangst_kg_m2_SMÅ)  |
                  diff_Fangst_kg_m2_STO != 0 | is.na(diff_Fangst_kg_m2_STO)  | 
                  diff_Fangst_kg_m2 != 0 | is.na(diff_Fangst_kg_m2))

# 
#| diff_fangst_oes_kg_m2_SMÅ != 0 | diff_fangst_oes_kg_m2_STO != 0
#| diff_fangst_oes_kg_m2 != 0 | diff_Korrigeret_oes_kg_m2 != 0

```

# Number of issues

`r nrow(Issue_2)`

```{r export, include = F}

write.csv(Issue_2,
          file = paste(dir_out, "Biomasse_",species,"_",v_new, "_vs_", v_old,"_",
                     format(Sys.time(), "%d%b%Y"),".csv",sep = ""),
          row.names=FALSE,fileEncoding = "UTF-8")

saveRDS(Issue_2,
          file = paste(dir_out, "Biomasse_",species,"_",v_new, "_vs_", v_old,"_",
                     format(Sys.time(), "%d%b%Y"),".rds",sep = ""))

```

