---
geometry: top=2cm, bottom=1.5cm, left=1.5cm, right=5cm
header-includes:
- \usepackage{tabularx}
- \usepackage{tcolorbox}
output: pdf_document
---

\renewcommand{\familydefault}{\sfdefault}
\sffamily

```{r define_input, echo=FALSE}


#Parameters
# year<- @paramYear
# cruise <- @paramCruise
# species <- @paramSpecies
# trip <- '1 OES' #trip number
# gearQuality <- "V"
# redsk_dim <- 1
# areaString <- 'Alle_muslingeområder_2019_region_erase1.shp'

year<- 2000
cruise <- 'BV LF BMS maj'
species <- "BMS"
gearQuality <- "V"
redsk_dim <- 1
areaString <- "Q:/gis/Dynamisk/GEOdata/BasicLayers/Boundaries/Muslingeomraader/Alle_muslingeområder_2019_region_erase1.shp"

```





```{r set_libraries, include=FALSE}

#Libraries
if (!require(pacman)) {
  install.packages("pacman", repos="http://ftp.ussg.iu.edu/CRAN/")
  library(pacman)
}

p_load(RODBC,dplyr,sf,data.table,stringr,lwgeom,knitr)

```

```{r getdata, echo=FALSE, message=FALSE, warning=FALSE}


channel <- odbcConnect("FishLineDW")
data <- sqlQuery(channel, paste("SELECT    Sample.sampleId, Sample.year, Sample.cruise, Sample.trip, Sample.remark, Sample.station, 
                                           Sample.stationName, Sample.dateGearStart, Sample.latPosStartText, Sample.lonPosStartText, 
                                           Sample.latPosStartDec, Sample.lonPosStartDec, Sample.distanceBottom,Sample.coursetrack,
                                           Sample.fishingtime, Sample.distancePositions, Sample.gearQuality, 
                                           SpeciesList.speciesCode, SpeciesList.weightStep0, 
                                           SpeciesList.weightStep1, SpeciesList.weightStep2, SpeciesList.weightStep3, 
                                           SpeciesList.raisingFactor, Animal.representative, Animal.individNum, Animal.length, 
                                           Animal.number, Animal.weight, SpeciesList.speciesListId, Animal.animalId, Sample.depthAveGear,
                                           Sample.gearType, Sample.depthAvg
                                 FROM      fishlineDW.dbo.Animal RIGHT OUTER JOIN
                                           fishlineDW.dbo.SpeciesList ON Animal.speciesListId = SpeciesList.speciesListId RIGHT OUTER JOIN
                                           fishlineDW.dbo.Sample ON SpeciesList.sampleId = Sample.sampleId
                                 WHERE     Sample.year = (",year, ") AND
                                           Sample.cruise = ('",cruise, "') AND
                                           Sample.gearQuality = 'V' ", sep=""), stringsAsFactors=FALSE)                         
close(channel)

    
```

```{r, echo=FALSE, warning=FALSE,message=FALSE}

data$stationType <- ifelse(data$gearType == "MSKOES" & !is.na(data$gearType),"BOS",
                      ifelse(data$gearType %like% "^OSK" & !is.na(data$gearType),"OES",
                      ifelse(data$gearType %like% "^MSK" & !is.na(data$gearType),"BMS", 
                      ifelse(data$gearType %like% "^RAM" & !is.na(data$gearType),"RAM",
                      ifelse(data$gearType %like% "^SUG" & !is.na(data$gearType),"SUG",
                      ifelse(data$gearType %like% "^VV" & !is.na(data$gearType),"VV","SST"))))))

data[grepl("\\d",(data$gearType)),"gearVal"] <-  as.numeric(substring(data[grepl("\\d",(data$gearType)),]$gearType, 4))


data[data$stationType=="SST","redsk_dim"] <- 2.4
data[data$stationType %in% c("BMS","OES","BOS"),"redsk_dim"] <- 1
data[!is.na(data$gearVal),"redsk_dim"] <- data[!is.na(data$gearVal),"gearVal"]/100
data[is.na(data$redsk_dim),"redsk_dim"] <- 1




```

```{r, echo=FALSE, warning=FALSE,message=FALSE}



#####################################################

#Calculate Befisket areal depending on species


data[data$coursetrack==0 & 
       !is.na(data$coursetrack),"coursetrack"] <- NA
data[data$distancePositions==0 & 
       !is.na(data$distancePositions),"distancePositions"] <- NA


#Areal = udsejlet distance* redskabsbredde (Hvis udsejlet distance er kendt)
data[!is.na(data$coursetrack) & 
       !(data$stationType %in% c('RAM','VV')) ,"Befisket_Areal_m2"] <- 
  data[!is.na(data$coursetrack) & 
         !(data$stationType %in% c('RAM','VV')) ,]$coursetrack * 
  data[!is.na(data$coursetrack) & 
         !(data$stationType %in% c('RAM','VV')) ,]$redsk_dim

data[!is.na(data$coursetrack) & 
       !(data$stationType %in% c('RAM','VV')) ,"areal_metode"] <- "Udsejlet distance"
  
#Areal = Distance*redskabsbredde (Hvis Distance ≠0 og courstrack=NA)
data[!is.na(data$distancePositions) &
       is.na(data$coursetrack) & 
       !(data$stationType %in% c('RAM','VV')) ,"Befisket_Areal_m2"] <- 
  data[!is.na(data$distancePositions) &
         is.na(data$coursetrack) & 
         !(data$stationType %in% c('RAM','VV')) ,]$distancePositions*1852*
  data[!is.na(data$distancePositions) & 
         is.na(data$coursetrack) & 
         !(data$stationType %in% c('RAM','VV')) ,]$redsk_dim

data[!is.na(data$distancePositions) & 
       is.na(data$coursetrack) & 
       !(data$stationType %in% c('RAM','VV')) ,"areal_metode"] <- "Distance start-slut"

#Areal = træktid*træhastighed*redskabsbredde (Distance=0 og udsejlet distance ukendt), distanceBottom= Trækhast*fisketid i sømil (haulSpeedBot*fishingtime).
data[is.na(data$distancePositions) &
       is.na(data$coursetrack) & 
       !(data$stationType %in% c('RAM','VV'))  ,"Befisket_Areal_m2"] <- 
  data[is.na(data$distancePositions) &
         is.na(data$coursetrack) & 
         !(data$stationType %in% c('RAM','VV')) ,]$distanceBottom*1852*
  data[is.na(data$distancePositions) & 
         is.na(data$coursetrack) & 
         !(data$stationType %in% c('RAM','VV')),]$redsk_dim

data[is.na(data$distancePositions) & 
       is.na(data$coursetrack) &
       !(data$stationType %in% c('RAM','VV')),"areal_metode"] <- "Træktid*trækhastighed"

#Areal = rammeareal (Hvis redskab=ramme)
data[data$gearType %like% '^RAM' & 
       data$gearType!="RAM" & 
       !is.na(data$gearType),"Befisket_Areal_m2"] <-
  data[data$gearType %like% '^RAM' &
         data$gearType!="RAM" & 
         !is.na(data$gearType),]$redsk_dim

data[data$gearType=="RAM" &
       !is.na(data$gearType),"Befisket_Areal_m2"] <- 0.01
data[data$gearType %like% '^RAM' & 
       !is.na(data$gearType),"areal_metode"] <- "Ramme-areal"


#Areal = sugeareal (Hvis redskab=sug)
data[data$gearType %like% '^VV' & 
       !is.na(data$gearType),"Befisket_Areal_m2"] <- 
  data[data$gearType %like% '^VV' &
         !is.na(data$gearType),]$redsk_dim

data[data$gearType %like% '^SUG' & 
       !is.na(data$gearType),"areal_metode"] <- "Suge-areal"



######################################################


data2 <- data[data$speciesCode==species,]

data2$TotalWeight_kg <- as.numeric(apply(data2[,c("weightStep0","weightStep1","weightStep2","weightStep3")], 
                                        1, function(x) min(x[1], x[2], x[3], x[4], na.rm=TRUE)))*data2$raisingFactor

data2$TotalNumber <- data2$number*data2$raisingFactor
data2$Length_cm <- data2$length/10
data2$SOP_Length <- data2$Length_cm*data2$number*data2$raisingFactor

index <- data2$speciesCode!=species
data2$speciesCode[index==TRUE] <- "AAA"
data2$Length_cm[index==TRUE] <- NA; data2$TotalWeight_kg[index==TRUE] <- NA; data2$TotalNumber[index==TRUE] <- NA


```

```{r OES , echo=FALSE, warning=FALSE,message=FALSE}


if (species=="OES") {

data2$fastst <- apply(data2[,c("stationName","year","remark")], 1, function(x) 
                   if (is.na(x[1]) & x[2]!= 2006 & grepl("KM", x[3])==FALSE) { gsub("[^0-9]","",x[3])}
              else if (is.na(x[1]) & x[2]== 2006 & grepl("A", x[3])==FALSE) { gsub("[^0-9]","",x[3])}
              else if (is.na(x[1])) {substr(x[3],8,12) }
              else {NA})
data2[is.na(data2$stationName),"stationName"] <- data2[is.na(data2$stationName),"fastst"] 

data3 <- data2[!(grepl("KM", data2$remark)==TRUE),]

} else {data3 <- data2}


```
  
```{r, include=FALSE}
  sf::sf_use_s2(FALSE)
  MUSOMR <- st_read(areaString,stringsAsFactors = F) %>%
    st_transform(crs=4326)
  MUSOMR <- MUSOMR %>% select(OMRådENUM,OMRådENAV)

  data3$lat <- data3$latPosStartDec
  data3$lon <- data3$lonPosStartDec

  data5 <- st_as_sf(data3[!is.na(data3$lon) & !is.na(data3$lat), ], 
                    coords = c("lon","lat"),crs = 4326)

  data6 <- st_join(data5, MUSOMR)

  st_geometry(data6) <- NULL
  data_omr2 <- data6 %>%
    # select(-AREAL,-STATUS,-Area_km2,-Nr,) %>%
    as.data.frame()
  
```



```{r, echo=FALSE, warning=FALSE,message=FALSE}

data_table <- data_omr2 %>%  
  group_by(sampleId, stationType, year, cruise, trip, station, stationName, dateGearStart,
           latPosStartText,lonPosStartText, latPosStartDec, lonPosStartDec, OMRådENUM,
           OMRådENAV, fishingtime, depthAvg, depthAveGear, Befisket_Areal_m2, areal_metode,
           speciesCode,TotalWeight_kg, Length_cm) %>% 
  summarise(Number = sum(TotalNumber,na.rm=T))

# st_geometry(data_table)<-NULL  

```

\section{Data - Længdefordeling}

\begin{tcolorbox}[colback=white!5,colframe=blue!40!black,title=Information om udtrækket]
\renewcommand{\arraystretch}{1.2}
\begin{tabularx}{15cm}{@{}lXr@{}}
\textbf{År} & `r year` &\\ 
\textbf{Togt} & `r cruise`&\\
\textbf{Art} & `r species`&\\
\textbf{Redskabsdimension} & `r species` &
\end{tabularx}
\end{tcolorbox}

```{r, echo=FALSE, warning=FALSE,message=FALSE,results='asis'}

#Write csv
cruise <- gsub(" ","_",cruise)
write.csv(data_table, 
          file=sprintf("Længdefordeling_%s_%s_%s_Længde_%s.csv",
                       year,cruise,species,format(Sys.time(), "%d%b%Y",)),
          row.names=FALSE)

# cat("\\subsection{Info om shapefil} ")
# cat("I længdefordelingen bruges en shapefil til at tildele de enkelte stationer et områdenavn. 
# Tabellen nedenfor viser de fejl, som shapefilen indeholder i kolonnen 'val' og hvordan validiteten 
# er efter at have kørt en automatiseret validering af samme område i kolonnen 'val_made_lvaid'.")
# mus_omr$val <- as.character(st_is_valid(mus_omr,reason = T))
# mus_omr2$val_made_valid <- as.character(st_is_valid(mus_omr2,reason = T))
# 
# st_geometry(mus_omr)<-NULL
# st_geometry(mus_omr2)<-NULL
# 
# mus_omr %>%
#   select(Area,val) %>%
#   full_join(mus_omr2 %>% select(Area,val_made_valid)) %>%
#   mutate(Area = as.numeric(Area)) %>%
#   arrange(Area) %>%
#   filter(val != "Valid Geometry" | is.na(val)) %>%
#   kable()
```

<!-- Biomasse-længdefordeling -->