
---
fontsize: 12pt
geometry: top=2cm, bottom=2cm, left=2cm, right=2cm,headsep=1cm
header-includes:
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage[T1]{fontenc}
- \usepackage[danish]{babel}
- \usepackage[utf8]{inputenc}
- \usepackage{lastpage}
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \fancyhf{}
- \fancyfoot{}
output:
  pdf_document: default
  word_document: default
  fig_caption: false
---

\renewcommand{\familydefault}{\sfdefault}
\sffamily

```{r define_input, include=F}
writeCatchTrip <- @paramCatchTrip
writeResp <- @paramResp
writeRespCatch <- @paramRespCatch
prefix <- ""


# writeCatchTrip <- "all" #or "all" or "no"
# writeResp <- "yes" # or "yes"
# writeRespCatch <- "yes" #or "yes"
# prefix <- ""
# setwd("M:/123 - FiskeLine/Rapporter/Rapporter/Rekrea")
```

\lhead{\footnotesize Rekrea: Østersølaks}
\rhead{\footnotesize Udskrevet: \today }
\fancyfoot[R]{\thepage/\pageref{LastPage}}

\section{Østersølaks}

```{r libraries, include=F}
# This script downloads data related to the baltic salmon sub project and arranges it into
# csv files with trip information, catch information (both suitable for fiskeline)
# survey responses and a mix of catch and surveyresponses.
# 
# Because data is entered on a tablet in often poor conditions, you will need to 
# manually go through the data in order to spot typos and errors.
#
# Data comes from SurveyGizmo in exports named "auto export" for each survey. 
# In this script they will be stitched together and prepared for upload to Fiskeline.
#
# When a trip has been imported to Fiskeline, it will be ignored in later imports. So if there
# are any changes in the trip data or the responses in the trip, tey will not be uploaded.
# Therefore: make sure data is cleaned before importing it to Fiskeline!

# This script takes the laks i østersøen survey data and creates csv
# files for trip, catch, responses and respcatch (merge og response and catch)
#
# Unlike the data from the COD23 survey, all data from the salmon survey is
# arranged in a single file in the survey program, making the survey more simple
# to work with.
#
# You will still need to look thorugh the data to find typos etc - especially in 
# the catch and trip files.


# Reading and loading libraries -------------------------------------------

if (!require("pacman")){
    install.packages("pacman")
    library(pacman)
}

# p_load loads and, if necessary, installs missing packages
p_load(grid,stringr,directlabels,gridExtra,scales,ggplot2,dplyr,knitr,xtable,
       data.table,tidyr,xlsx,lubridate,zoo,uuid,stringi,RODBC,rvest,uuid,jsonlite,httr,
       ggrepel,kableExtra)

#setwd("Q:/mynd/RekreativtFiskeri/REKREA/")
# source("./programs/get_rekrea_libraries.R")
source("get_rekrea_functions.R")
# source("./programs/downloader.R")
```


```{r downloadData, include=F}
channel <- RODBC::odbcConnect("FishLineDW")

knownTrips <- sqlQuery(channel,  
                       "select trip from Trip where cruise = 'rekrea laks' and year < 2100",
                       stringsAsFactors=F)
close(channel)

# download latest export -----
downloadSurvey <- function(key,pwd){
    
    url <- paste0("https://data.surveygizmo.com/reportsview/?key=",key)
    pgsession <- html_session(url)
    pgform <- html_form(pgsession)[[1]]
    
    filled_form <- set_values(pgform,
                              `password`=pwd)
    a <- submit_form(pgsession,filled_form)
    b <- a$response$content
    C <- rawToChar(b)
    Encoding(C) <- "UTF-8"
    if (C != "\n"){
        d <- read.table(text = C,header = T,sep = ",",stringsAsFactors = F,
                        encoding = "UTF-8")
    } else{
        d <- NULL
    }
    
    
    return(d)
}

# links and passwords for data exports - because this does not belong on github
exports <- read.csv("laks_data_for_downloader.csv",sep = "\t",stringsAsFactors = F)

# download the latest exports from SG
for (u in 1:nrow(exports)){

  varName <- exports$varName[u]
  uuid <- exports$uuid[u]
  pw <-   exports$pw[u]

  cat(paste0(varName,"\n"))
  assign(varName,
           value = downloadSurvey(uuid,pw))

}
```


```{r readData, include=F}
# Read data ---------------------------------------------------------------

# LAKS <- laks0
# LAKS <- read.csv("./data_in/laks/laks.csv", 
#                 encoding="UTF-8",stringsAsFactors=FALSE)
    
laks <- unique(laks0[laks0$User.Agent %like% "SurveyGizmo REST API" &
                       laks0$Status=="Complete",
                     c(1,4,9,22:ncol(laks0))])


names(laks)[4:11]<-c("interviewer","other_interviewer","date","ices_sd","havn",
                      "c:spm1_4","long_short","update_catch")

laks <- laks %>% 
  filter(!(tolower(havn)) %in% c("xx","test"))

zipcodes <- data.frame(havn = c("Rønne","Rønne (Sdr. Bådehavn)",
                                "Rønne erhvervshavn","Rønne (Nørrekås)",
                                "Hasle","Sandvig","Allinge","Hammerhavn",
                                "Tejn","Nexø","Snogebæk","Årsdale","Listed",
                                "Melsted","Svaneke","Gudhjem (Nørresand)",
                                "Klintholm","Hesnæs","Arnager","Christiansø"),
                       postnr_havn = c(3700,3700,3700,3700,3790,3770,3770,3770,
                                       3760,3730,3730,3740,3740,3760,3740,3760,
                                       4791,4850,3700,3761),
                       stringsAsFactors = F
)

channel <- RODBC::odbcConnect("FishLineDW")

ages <- RODBC::sqlQuery(channel,
                        "SELECT
                        a.animalId
                        ,a.[station] as respNum
                        ,sam.sgId
                        ,a.trip as tripId
                        ,a.landingCategory
                        ,a.[speciesCode] as species
                        ,a.individNum
                        ,a.length
                        ,a.weight
                        ,a.number
                        ,a.[catchNum]
  FROM [FishLineDW].[dbo].[Animal] as a
  left join [FishLineDW].[dbo].[Sample] as sam
  on a.year = sam.year
  and a.cruise = sam.cruise
  and a.trip = sam.trip
  and a.station = sam.station
  where a.cruise = 'rekrea laks' and a.year < 2100",
                        stringsAsFactors = F)

knownTrips <- sqlQuery(channel,  
                       "select trip from Trip where cruise = 'rekrea laks' and year < 2100",
                       stringsAsFactors=F)

species <- sqlQuery(channel,  
                       "select speciesCode, dkName from L_Species",
                       stringsAsFactors=F)

close(channel)
```


```{r dataCleaning, include=F}
# Cleanup data ------------------------------------------------------------

laks[laks=="" | laks == " "] <- NA
laks$Response.ID <- paste0("LAKS",as.character(laks$Response.ID))

laks <- laks[!laks$Response.ID %in% c("LAKS50","LAKS62","LAKS37","LAKS104","LAKS105","LAKS106"),]
# trip nr : f:spm1_1
# intercept nr : b:spm1_1

laks$platform <- 
    ifelse(laks$Referer=="http://www.surveygizmo.com/s3/3522236/LaksOnsite",
           "Online","Offline")

laks$ices_sd <- trimws(laks$ices_sd)
laks$ices_sd[laks$ices_sd=="Christiansø"]<-"25"
laks$ices_sd[laks$ices_sd=="2018"]<-"24"
laks$ices_sd[laks$ices_sd=="20"]<-"24"


laks$date <- trimws(laks$date)
laks$date <- str_replace_all(laks$date,"(\\d+)\\D(\\d+)\\D(\\d+)","\\1/\\2/\\3")
laks$date <- paste(str_pad(str_split(laks$date,"/",simplify = T)[,1],width = 2,side="left",pad = "0"),
                   str_pad(str_split(laks$date,"/",simplify = T)[,2],width = 2,side="left",pad = "0"),
                   str_split(laks$date,"/",simplify = T)[,3],sep="/")
laks$date[laks$date=="07/)1/2018"]<-"04/01/2018"
laks$date[laks$date=="08/04/20 18"]<-"08/04/2018"
laks$date[laks$date=="08/04/2018 "]<-"08/04/2018"
laks$date[laks$date=="08/04@2018"]<-"08/04/2018"
laks$date[laks$date=="07/02/2018 "]<-"07/02/2018"
laks$date[laks$date=="Xxxx"]<-"11/01/2018"
laks$date[laks$date=="25/03/2918"]<-"25/03/2018"
laks$date[laks$date=="31/03/2018 "]<-"31/03/2018" 
laks$date[laks$date=="6/05/2018"]<-"06/05/2018"
laks$date[laks$date=="8/05/2018"]<-"08/05/2018"
laks$date[laks$date=="24/11/2028"]<-"24/11/2018"
laks$date[laks$date=="06/01/2017"]<-"06/01/2018"


laks$havn<-trimws(laks$havn)
laks$havn[grep(".ønne",laks$havn)]<-"Rønne"
laks$havn[tolower(laks$havn)=="adresse.  bådehavn rønne"]<-"Rønne (Sdr. Bådehavn)"
laks$havn[tolower(laks$havn)=="arnager"]<-"Arnager"
laks$havn[tolower(laks$havn)=="sdr bådehavn"]<-"Rønne (Sdr. Bådehavn)"
# laks$havn[laks$havn=="Sdr Bådehavn"]<-"Rønne (Sdr. Bådehavn)"
laks$havn[tolower(laks$havn)=="hammeren"]<-"Hammerhavn"
laks$havn[tolower(laks$havn)=="neksø"]<-"Nexø"
laks$havn[tolower(laks$havn)=="nørrekås"]<-"Rønne (Nørrekås)"

laks$ices_sd[laks$ices_sd=="Xx"]<-"24"

laks$dateYMD <- format(as.Date(laks$date,format="%d/%m/%Y"),"%Y%m%d")
laks$dateY <- format(as.Date(laks$date,format="%d/%m/%Y"),"%Y")
laks$dateQ <- lubridate::quarter(as.Date(laks$date,format="%d/%m/%Y"))
laks$dateM <- format(as.Date(laks$date,format="%d/%m/%Y"),"%m")
laks$dateD <- format(as.Date(laks$date,format="%d/%m/%Y"),"%d")
laks$weekdayWeekend <- 
    ifelse(lubridate::wday(as.Date(laks$date,format="%d/%m/%Y")) %in% c(1,7),
           "Weekend","Hverdag")

laks$interviewer[laks$interviewer=="" & 
                     laks$dateYMD == 20180214]<-"Anders Schou"
laks$interviewer[laks$Response.ID=="LAKS207"]<-"Anders Schou"
laks$interviewer[laks$Response.ID=="LAKS70"]<-"Anders Schou"


laks$Observer <- ifelse(laks$other_interviewer=="", 
                        laks$interviewer, laks$other_interviewer)
laks$Observer[laks$Observer=="Anders Schou"]<-"ansj"
laks$Observer <- toupper(laks$Observer)

# a <- data.frame(a = c(1,1,2,2), b = c(NA,400,NA,100), c = c(NA,NA,NA,1111))
# a; h <- a %>% group_by(a) %>% fill(everything(),.direction="up"); h

rowsToBeMerged <- laks[(laks$date=="24/03/2018" & laks$havn=="Tejn") | 
                           (laks$date=="28/12/2017" & laks$havn=="Tejn"),]

# laks <- laks[(laks$date=="24/03/2018" & laks$havn=="Tejn") | 
#          (laks$date=="28/12/2017" & laks$havn=="Tejn"),]

rowsToBeMerged[rowsToBeMerged==""]<-NA

h <- rowsToBeMerged %>%
    group_by(date,havn) %>% 
    fill(everything(),.direction = "up") %>% 
    filter(row_number()==1) 



laks2 <- laks[!laks$Response.ID %in% unique(rowsToBeMerged$Response.ID),]
laks3 <- laks#bind_rows(laks2,h)


# Create identifiers for trips, intercepts and responses

tripId <- laks3 %>% 
    arrange(Response.ID) %>% 
    select(date,dateYMD,Observer,havn,ices_sd) %>% 
    distinct() %>% 
    unite(do,dateYMD,Observer,remove = F) %>% 
    # arrange(do) %>%
    mutate(tripNum = dense_rank(do)) %>% 
    group_by(do) %>% 
    mutate(Trip.ID = paste(paste0(tripNum,"r"),1:n(),sep="_")) %>% 
    ungroup() %>% 
    select(-do,-tripNum)
           
    # group_by(date,Observer) %>% 
    # mutate(Trip.ID = paste0(1:n(),"-",Observer,"-",date))
        

laks3b <- left_join(laks3, tripId)

laks3b <- laks3b %>%
    group_by(Trip.ID) %>% 
    mutate(Intercept.ID = 1:n(),
           startHour = as.numeric(str_split_fixed(a.spm3_2,
                                            pattern = "[.,]",
                                            2)[,1]),
           startMin = ifelse(b.spm3_2=="",
                             as.numeric(str_split_fixed(a.spm3_2,
                                                  pattern = "[.,]",
                                                  2)[,2]),
                             as.numeric(b.spm3_2)),
           endHour = as.numeric(str_split_fixed(a.spm3_3,
                                          pattern = "[.,]",
                                          2)[,1]),
           endMin = ifelse(b.spm3_3=="",
                           as.numeric(str_split_fixed(a.spm3_3,
                                                pattern = "[.,]",
                                                2)[,2]),
                           as.numeric(b.spm3_3))
           ) %>% 
    mutate(startHour = str_pad(ifelse(is.na(startHour),8,startHour),
                               width = 2,side = "left",pad = 0),
           startMin = str_pad(ifelse(is.na(startMin),0,startMin),
                              width = 2,side = "left",pad = 0),
           endHour = str_pad(ifelse(is.na(endHour),16,endHour),
                             width = 2,side = "left",pad = 0),
           endMin = str_pad(ifelse(is.na(endMin),0,endMin),
                            width = 2,side = "left",pad = 0))
    # group_by(havn) %>% 
    # mutate(Intercept.ID = 1:n())

# laks3$Trip.ID <- paste0(laks3$dateYMD,"_",laks3$Observer)

# laks3b$Intercept.ID <- with(laks3b, ave(dateYMD,dateYMD,Observer, FUN = seq_along))
```


```{r tripData, include=F}
# Trip data ---------------------------------------------------------------

laks4 <- left_join(laks3b,zipcodes,by="havn") %>% 
    mutate(dateGearStart = sprintf("%s-%s-%s %s:%s:00",
                                   dateY,dateM,dateD,startHour,startMin),
           dateGearEnd = sprintf("%s-%s-%s %s:%s:00",
                                 dateY,dateM,dateD,endHour,endMin),
           interviewer = case_when(interviewer=="Anders Schou" ~ "ANSJ",
                                   interviewer=="Andern" ~ other_interviewer,
                                   TRUE ~ "ANSJ")) %>% 
    select(-startHour,-startMin,-endHour,-endMin,-dateD)

trip_data_long <- laks4 %>% 
    group_by(Trip.ID) %>% 
    dplyr::summarize(
        "dateYMD"=unique(dateYMD),
        "sgTRid"=unique(Trip.ID),
        "caseStudy"="Laks",
        "tripId"= unique(Trip.ID),#,"_",ices_sd,"_",havn)),
        "tripNum"="",
        "tripType" = "Havn",
        "dateStart" = unique(date),
        "year" = unique(dateY),	
        "quarterStart" = unique(dateQ),
        "weekdayWeekend" = unique(weekdayWeekend),	
        "dfuArea" = unique(ices_sd),	
        "placeName" = unique(havn),	
        "placeCode" = "",
        "postalCode" = unique(postnr_havn),
        "numberInPlace" = sum(Antal.fiskere.i.båden),  # exclude rows with post survey catch upd.
        "respYes" = sum(spm2_1=="Ja"),
        "respNo" = sum(spm2_1=="Nej"),
        "respTot" = respYes+respNo,
        "interviewPerson" = unique(interviewer)) 

trip_data_long2 <- trip_data_long %>% 
    arrange(dateYMD, sgTRid) %>% 
    select(-dateYMD,-Trip.ID)
# names(trip_data)<-c("sgTRid","caseStudy","tripId",tripNum	tripType	dateGearStart	year	quarterGearStart	weekdayWeekend	dfuArea	placeName	placeCode	postalCode	numberInPlace	respYes	respNo	respTot	interviewPerson
# # )

colnames(laks4) <- str_replace_all(colnames(laks4),"æ","ae")
colnames(laks4) <- str_replace_all(colnames(laks4),"ø","oe")
colnames(laks4) <- str_replace_all(colnames(laks4),"å","aa")
colnames(laks4) <- str_replace_all(colnames(laks4),"Æ","Ae")
colnames(laks4) <- str_replace_all(colnames(laks4),"Ø","Oe")
colnames(laks4) <- str_replace_all(colnames(laks4),"Å","Aa")
colnames(laks4) <- str_replace_all(colnames(laks4),"é","e")
```


```{r respData, include=F}
# Resp data ---------------------------------------------------------------
if (writeResp == "yes" | writeRespCatch == "yes"){
  resp_laks <- laks4 %>%
      group_by(Trip.ID,Intercept.ID) %>%
      dplyr::summarise(
          sgId = Response.ID,
          tripId = Trip.ID,
          tripNum = "",
          date = date,
          month = dateM,
          quarter = dateQ,
          year = dateY,
          tripType = "Havn",
          weekdayWeekend = weekdayWeekend,
          interviewPerson = Observer,
          place = havn,
          respNum = Intercept.ID,
          statusInterview = Status,
          longShort = long_short,
          timeInterviewEnd = timeMaker(a.spm1_5,b.spm1_5),
          participateSurvey = spm2_1,
          participatedBefore = a.spm3_1,
          participatedWhen = b.spm3_1,
          tripStart = timeMaker(a.spm3_2,b.spm3_2),
          tripEnd = timeMaker(a.spm3_3,b.spm3_3),
          # noeHours = "",
          # coeHours = "",
          # soeHours = "",
          license = spm3_5 ,
          licenseType = spm3_5.2,
          noLicense = spm3_5.3,
          target1 = Maalart.1.spm3_6,
          target2 = Maalart.2.spm3_6,
          target3 = Maalart.3.spm3_6,
          target4 = Maalart.4.spm3_6,
          target5 = Maalart.5.spm3_6,
          catchRegistartion = "",
          
          tripsTrolling12 = Antal.dage.a.spm4_1.1,
          tripsTrolling3 = Antal.dage.b.spm4_1.1,
          
          tripsOtherfishing12 = Antal.dage.Hvis.du.ikke.medregner.i.dag..hvor.mange.dage.har.du.saa.inden.for.de.sidste.12.mdr..vaeret.paa.en.eller.anden.form.for.fisketur..spm4_2.1,
          tripsOtherfishing3 = Antal.dage.Hvis.du.ikke.medregner.i.dag..hvor.mange.dage.inden.for.de.sidste.3.mdr...spm4_2.1,
          
          reasonForFishingTodayEnjoyNature = priority(At.nyde.naturen.Hvad.var.de.tre.vigtigste.grunde.til.at.du.tog.paa.fisketur.efter.laks.i.dag..Her.skal.du.kun.vaelge.et.svar.per.soejle...),
          reasonForFishingTodayCatchForEating = priority(At.fange.en.fisk.jeg.kan.spise.Hvad.var.de.tre.vigtigste.grunde.til.at.du.tog.paa.fisketur.efter.laks.i.dag..Her.skal.du.kun.vaelge.et.svar.per.soejle...),
          reasonForFishingTodayRelax = priority(At.slappe.af.Hvad.var.de.tre.vigtigste.grunde.til.at.du.tog.paa.fisketur.efter.laks.i.dag..Her.skal.du.kun.vaelge.et.svar.per.soejle...),
          reasonForFishingTodayForTheExcitement = priority(At.opleve.spaendingen.ved.at.fange.en.fisk.Hvad.var.de.tre.vigtigste.grunde.til.at.du.tog.paa.fisketur.efter.laks.i.dag..Her.skal.du.kun.vaelge.et.svar.per.soejle...),
          reasonForFishingTodayForTheChallenge = priority(At.nyde.udfordringerne.ved.at.fiske.Hvad.var.de.tre.vigtigste.grunde.til.at.du.tog.paa.fisketur.efter.laks.i.dag..Her.skal.du.kun.vaelge.et.svar.per.soejle...),
          reasonForFishingTodayToGetPeaceAndQuiet = priority(At.faa.fred.og.ro.Hvad.var.de.tre.vigtigste.grunde.til.at.du.tog.paa.fisketur.efter.laks.i.dag..Her.skal.du.kun.vaelge.et.svar.per.soejle...),
          reasonForFishingTodayToBeWithFamilyFriends = priority(At.vaere.sammen.med.familie.og.venner.Hvad.var.de.tre.vigtigste.grunde.til.at.du.tog.paa.fisketur.efter.laks.i.dag..Her.skal.du.kun.vaelge.et.svar.per.soejle...),
          reasonForFishingTodayCatchLotsOfFish = priority(At.fange.en.masse.fisk.Hvad.var.de.tre.vigtigste.grunde.til.at.du.tog.paa.fisketur.efter.laks.i.dag..Her.skal.du.kun.vaelge.et.svar.per.soejle...),
          reasonForFishingTodayImproveAnglingSkills = priority(At.udvikle.mine.faerdigheder.som.lystfisker.Hvad.var.de.tre.vigtigste.grunde.til.at.du.tog.paa.fisketur.efter.laks.i.dag..Her.skal.du.kun.vaelge.et.svar.per.soejle...),
          reasonForFishingTodayTestMyEquipment = priority(At.faa.testet.mit.fiskeudstyr.Hvad.var.de.tre.vigtigste.grunde.til.at.du.tog.paa.fisketur.efter.laks.i.dag..Her.skal.du.kun.vaelge.et.svar.per.soejle...),
          
          agreeDisagreeDontKnowWhatElseToDo = agreeing(Hvis.jeg.ikke.kunne.fiske..ville.jeg.ikke.vide.hvad.jeg.skulle.tage.mig.til.i.min.fritid.Hvor.enig.eller.uenig.er.du.i.foelgende.udsagn.),
          agreeDisagreeIKnowMostOfMyFriendsFromFishing = agreeing(De.fleste.af.mine.venner.kender.jeg.via.min.interesse.for.lystfiskeri..Hvor.enig.eller.uenig.er.du.i.foelgende.udsagn.),
          agreeDisagreeNoOtherInterestAsExcitingAsFishing = agreeing(Ingen.af.mine.andre.fritidsinteresser.er.saa.interessante.som.lystfiskeri..Hvor.enig.eller.uenig.er.du.i.foelgende.udsagn.),
          agreeDisagreeLifeCenteredAroundFishing = agreeing(Det.meste.af.mit.liv.er.centreret.omkring.lystfiskeri.Hvor.enig.eller.uenig.er.du.i.foelgende.udsagn.),
          
          agreeDisagreeB1BigRatherThan5Small = agreeing(Jeg.vil.hellere.fange.en.stor.laks.fremfor.fem.mindre....Med.udgangspunkt.i.dit.fiskeri.efter.laks.i.Oestersoeen..hvor.enig.eller.uenig.er.du.saa.i.foelgende.udsagn...),
          agreeDisagreeBOnlySuccessIfBroughtHome = agreeing(For.at.en.fisketur.har.vaeret.en.succes..skal.jeg.fange.og.hjemtage.en.laks....Med.udgangspunkt.i.dit.fiskeri.efter.laks.i.Oestersoeen..hvor.enig.eller.uenig.er.du.saa.i.foelgende.udsagn...),
          agreeDisagreeBTheBiggerSalmonTheBetterTrip = agreeing(Jo.stoerre.laks.jeg.fanger..jo.bedre.er.fisketuren....Med.udgangspunkt.i.dit.fiskeri.efter.laks.i.Oestersoeen..hvor.enig.eller.uenig.er.du.saa.i.foelgende.udsagn...),
          agreeDisagreeBNeedToCatchForSuccess = agreeing(Jeg.skal.fange.en.laks.for.at.turen.har.vaeret.en.succes....Med.udgangspunkt.i.dit.fiskeri.efter.laks.i.Oestersoeen..hvor.enig.eller.uenig.er.du.saa.i.foelgende.udsagn...),
          agreeDisagreeB1BigRatherThan10Small = agreeing(Jeg.vil.hellere.fange.en..stor.laks.fremfor.ti.mindre....Med.udgangspunkt.i.dit.fiskeri.efter.laks.i.Oestersoeen..hvor.enig.eller.uenig.er.du.saa.i.foelgende.udsagn...),
          agreeDisagreeBSuccessfullTripWhenCathingMany = agreeing(En.succesfuld.trollingtur.er.en.tur.hvor.jeg.fanger.mange.laks..Med.udgangspunkt.i.dit.fiskeri.efter.laks.i.Oestersoeen..hvor.enig.eller.uenig.er.du.saa.i.foelgende.udsagn...),
          agreeDisagreeBTripCanBeSuccessDespiteNoCatch = agreeing(En.trollingtur.kan.vaere.en.succes..selvom.jeg.ikke.fanger.nogen.laks....Med.udgangspunkt.i.dit.fiskeri.efter.laks.i.Oestersoeen..hvor.enig.eller.uenig.er.du.saa.i.foelgende.udsagn...),
          agreeDisagreeBJustAsSatisfiedWhenNotCatchingAnySalmon = agreeing(Paa.en.trollingtur..er.jeg.lige.saa.tilfreds.hvis.jeg.ingen.laks.fanger....Med.udgangspunkt.i.dit.fiskeri.efter.laks.i.Oestersoeen..hvor.enig.eller.uenig.er.du.saa.i.foelgende.udsagn...),
          agreeDisagreeBTheMoreSalmonCaughtTheHappierIAm = agreeing(Jo.flere.laks.jeg.fanger.paa.en.trollingtur..jo.mere.tilfreds.bliver.jeg..Med.udgangspunkt.i.dit.fiskeri.efter.laks.i.Oestersoeen..hvor.enig.eller.uenig.er.du.saa.i.foelgende.udsagn...),
          agreeDisagreeBMyTripSatisfactionIsTheSameEvenWhenIReleaseSalmon = agreeing(Min.tilfredshed.med.en.fisketur.er.den.samme..selvom.jeg.genudsaetter.laks....Med.udgangspunkt.i.dit.fiskeri.efter.laks.i.Oestersoeen..hvor.enig.eller.uenig.er.du.saa.i.foelgende.udsagn...),
          
          sliderHowOftenDoYouGoFishingOverOtherInterests = Naar.du.har.fritid.til.overs..hvor.ofte.vaelger.du.saa.at.tage.ud.at.fiske.frem.for.andre.fritidsinteresser...Placer.punktet.hvor.som.helst.paa.skalaen.hvor.det.er.rigtigt.for.dig..,
          sliderHowImportantIsAnglingForYourLifestyle = Hvor.vigtig.er.lystfiskeri.for.din.livsstil..f.eks..dit.sociale.liv..din.aktivitet.paa.sociale.medier..planlaegning.af.din.arbejdsdag..valg.af.feriemaal....Placer.punktet.hvor.som.helst.paa.skalaen.hvor.det.er.rigtigt.for.dig..,
          
          perfectTripAmount = c.spm9_3,
          perfectTripAmountUnit = d.spm9_3,
          perfectTripAmountYearsAgo = Hvor.laenge.er.det.siden..at.du.sidst.oplevede.at.fange.dette.antal.laks.paa.en.trollingtur...spm9_3,
          
          perfectTripSize = Paa.en.trollingtur.som.denne..hvor.stor.en.laks.skal.du.saa.fange.for.at.turen.har.vaeret.absolut.perfekt..skriv.0.hvis.det.ikke.betyder.noget.for.din.tilfredshed....spm9_4,
          perfecTripSizeUnit = Svarede.du.forrige.spoergsmaal.i.kilo.eller.cm..spm9_4,
          perfectTripSizeYearsAgo = Hvor.laenge.er.det.siden.du.sidst.fangede.saa.stor.en.laks..spm9_4,
          
          trollingImportanceAsHobby = priority2(spm8_4),
          
          satisfactionThisTrip = spm8_7,
          satisfactionThisTripAmount = spm8_7a,
          satisfactionThisTripSize = spm8_7b,
          
          ifRegulated1SalmonPerDay = agreeing2(Du.maa.hjemtage.max.1.laks.pr..dag.spm44),
          ifRegulated2SalmonPerDay = agreeing2(Du.maa.hjemtage.max.2.laks.pr..dag.spm44),
          ifRegulated3SalmonPerDay = agreeing2(Du.maa.hjemtage.max.3.laks.pr..dag.spm44),
          
          addressStatus = "",
          addressPostalCode = Postnummer.spm8_1,
          addressCity = By.spm8_1,
          addressStreet = Vejnavn.spm8_1,
          addressCountry = Udlaending..land..spm8_1,
          contactStatus = "",
          contactName = a.spm8_2,
          contactPhone = "",
          contactEmail = e.spm8_2,
          contactTime = "",
          contactAge = spm8_3,
          contactSex = spm8_4.1,
          ceParticipate = spm45,
          ceEmail = e.spm8_2,
          expertise = priority3(spm8_5),
          motivations = "",
          # rateTrip = "",
          fiskepleje = spm9_1,
          fangstjournalen = spm9_2,
          regFangstjournalen = spm9_2.2,
          # hobby = "",
          catchExpectations = "",
          # amountSatisfaction = "",
          # unitAmountSatisfaction  = "",
          # sizeSatisfaction = "",
          # unitSizeSatisfaction = "",
          transportMethod = a.spm9_4,
          carBrand = Hvilket.bil.fabrikat..spm9_4,
          fuelCar = Hvilket.drivmiddel.spm9_4,
          
          
          startHomeAdress = b.spm9_4,
          startSomewhereElseStreet = Gade.Hvis.turen.ikke.startede.paa.din.hjemmeadresse..hvor.startede.den.saa.fra..spm9_4,
          startSomewhereElseCity = By.Hvis.turen.ikke.startede.paa.din.hjemmeadresse..hvor.startede.den.saa.fra..spm9_4,
          startSomewhereElseZip = Postnummer.Hvis.turen.ikke.startede.paa.din.hjemmeadresse..hvor.startede.den.saa.fra..spm9_4,
          transportLength = c.spm9_4,
          numberInCar = d.spm9_4,
          transportOtherPurposes = f.spm9_4,
          transportHours = round(Timer.spm31+(Minutter.spm31/60),1),
          
          expensePublicTransportDKK = Forbrugt.i.DKK.Offentlig.transport..bus..tog.m.m...spm9_5,
          expensePermitsDKK = Forbrugt.i.DKK.Udgift.til.baad..benzin..ramper..havnegebyr.etc..spm9_5,
          expenseSmallGearDKK = Forbrugt.i.DKK.Agn.endegrej.div...f.eks..madding..line..kroge..blink.mm...spm9_5,
          expenseLargeGearDKK = Forbrugt.i.DKK.Andet.fiskegrej.indkoebt.til.dagens.tur..f.eks..fiskestang..hjul..fangstnet..spm9_5,
          expenseFoodDKK = Forbrugt.i.DKK.Maaltider.snacks.som.ikke.er.inkluderet.i.tur.overnatning.spm9_5,
          expenseOtherEquipmentDKK = Forbrugt.i.DKK.Andet.udstyr.f.eks..fiskeguide.spm9_5,
          expenseAccommodationDKK = Forbrugt.i.DKK.Overnatning....angivet.pr..nat.spm9_5,
          expenseOtherDKK = Forbrugt.i.DKK.Andet.ikke.angivet.her..spm9_5,
          
          sgCEId = "",
          dateSubmitted = "",
          name = "",
          contactEmailCE = "",
          phone = "",
          situation1 = "",
          situation2 = "",
          situation3 = "",
          situation4 = "",
          situation5 = "",
          situation6 = ""
      ) %>% 
      arrange(as.Date(date,format="%d/%m/%Y"))
}
```


```{r catchData, include=F}
# Catch Data --------------------------------------------------------------

# make long table from laks4
# laks5 <- laks4 %>% 
#     select(c(1,6,15,80:112,114:218,272:ncol(laks4))) %>% 
#     gather(key, value, 
#            -Observer, -Response.ID,-date,-spm26_1,-spm5_1,
#            -Har.du.hjemtaget.nogle.fisk..spm22,-Trip.ID,-Intercept.ID, 
#            -Målart.1.spm3_6) %>% 
#     # filter(!is.na(value) & value!="") %>% 
#     arrange(Trip.ID,Intercept.ID)

laks5 <- laks4 %>% 
    # select(-Status,-Referer) %>% 
    select(c(1,6,7,17,82:114,115:220,274:276,278,279)) %>%
    # select(c(1,6,7,15,80:112,114:218,272:274,276,277)) %>%
    gather(key=key, value=value, -Observer, -Response.ID,-date,-spm26_1,-spm5_1,
           -Har.du.hjemtaget.nogle.fisk..spm22,-Trip.ID,-Intercept.ID, 
           -Maalart.1.spm3_6,-ices_sd,-dateGearStart,-dateGearEnd,
           -Vil.det.vaere.ok..hvis.jeg.tager.et.naermere.kig.paa.dine.fisk.og.maaler.og.vejer.dem...spm22
           ) %>% 
    # filter(!is.na(value) & value!="") %>% 
    arrange(Trip.ID,Intercept.ID)

# extract useful data from key
laks5$availability <- ifelse(str_detect(laks5$key,"spm5_1\\.2"),"Unavailable","Available")
laks5$catch.ID <- str_extract(str_extract(laks5$key,"(\\d+)\\.spm"),"\\d+")
laks5$key <- str_remove(str_extract(laks5$key,"(.+?)\\."),"\\.")

# make slightly wider table (1 fish per row)
laks6 <- laks5 %>% 
    spread(key = key,value = value)

# clean up data 
laks6$Vaegt[laks6$Vaegt=="5%2C16"]<-"5,16"
laks6$Vaegt[laks6$Vaegt=="111,2"]<-"11,2"
laks6$Laengde[laks6$Laengde=="881"]<-"88,1"
laks6$Art[laks6$Art=="1111"]<-1
laks6$Artskode[laks6$Artskode=="LAK"]<-"LKS"

# convert to numbers
laks6$length<- as.numeric(str_replace(laks6$Laengde,",","\\."))
laks6$weight <- as.numeric(str_replace(laks6$Vaegt,",","\\."))
laks6$Art <- as.numeric(laks6$Art)
laks6$Antal <- as.numeric(laks6$Antal)

colnames(laks6)[7]<-"hjemtaget..spm22"
colnames(laks6)[8]<-"okKig..spm22"

# laks6$Artskode[laks6$Artskode==""]<-"LAK"

# includes respondents that did not catch anything
# laks6$number <- ifelse((laks6$catch.ID==1 & 
#                         laks6$spm26_1=="Nej" & 
#                         laks6$availability == "Unavailable"),
#                        0,
#                        laks6$Antal)
laks6 <- laks6 %>% 
    mutate(number = case_when(catch.ID==1 & spm26_1 == "Nej" & 
                                  availability=="Unavailable" ~ 0,
                          # catch.ID==1 & hjemtaget..spm22 == "Ja" & 
                          #     okKig..spm22 == "Nej" & availability=="Available" ~ 1,  # fordi vi ikke må se deres fangst
                          catch.ID==1 & spm26_1 == "Ja" & hjemtaget..spm22 == "Nej" & 
                              availability=="Available"~ 0,
                          # hjemtaget..spm22 == "Ja" & okKig..spm22 == "Nej" ~ ,
                          TRUE ~ Antal))

laks6$targetSpecies <- ifelse(is.na(laks6$Art),
                              laks6$Maalart.1.spm3_6,
                              laks6$Art)
laks6$targetSpecies[laks6$targetSpecies=="1"]<-"Laks"
laks6$Artskode <- ifelse(is.na(laks6$Artskode),"LKS", toupper(laks6$Artskode))


laks6$catchCategory <- case_when(laks6$availability=="Available" ~ "C",
                                 laks6$availability=="Unavailable" & laks6$Antal > 0 ~ "R",
                                 laks6$availability=="Unvailable" & 
                                     laks6$hjemtaget..spm22=="Ja" &
                                     laks6$okKig..spm22=="Nej" & 
                                     laks6$Antal == 1 ~ "C")
laks6$Kode[laks6$Kode=="D"]<-4
laks6$samples <- ifelse(laks6$Proever=="","N","Y")

codesSpecies <- 
    data.frame(code = 1:6, 
               speciesCode = c("LKS","TOR","HOF","ORD","FLX","AAA"),
               dkName = c("Laks","Torsk","Hornfisk","Havørred","Fladfisk","Andet"), 
               stringsAsFactors = F)

laks6b <- left_join(laks6,codesSpecies, by=c("Art"="code")) %>% 
    filter(!is.na(number))

# laks6b <- left_join(laks6,species, by=c("Artskode" = "speciesCode")) %>% 
#   left_join(codesSpecies,by=c("Art"="code"))

laks7 <- laks6b %>% 
    filter(!(Response.ID=="LAKS155" & catch.ID=="1" & availability=="Unavailable"))


catch_data <- laks7 %>% 
    group_by(Trip.ID,Intercept.ID,availability,catch.ID) %>% 
    dplyr::summarise(
        sgId = Response.ID,
        tripId = unique(Trip.ID),
        respNum = unique(Intercept.ID),
        catchNum = catch.ID,
        speciesCode = ifelse(is.na(speciesCode),"LKS",speciesCode),
        catchCategory = ifelse(number==0,"C",catchCategory),
        number = number,
        length = length,
        weight = weight,
        code = Kode,
        otolith = samples,
        age = "",
        treatment = "UR",
        representative = "nej",
        stepNum = 0,
        ageMeasureMethod = "ØrestensAflæsning",
        dfuArea = unique(ices_sd),
        dateGearStart = as.POSIXct(unique(dateGearStart)[1],tz="UTC",origin="1970-01-01"),
        dateGearEnd = as.POSIXct(unique(dateGearEnd)[1],tz = "UTC",origin="1970-01-01"),
        tripResp = paste(tripId,sgId,sep="-")
    ) %>% 
    ungroup()

catch_data$landingCategory <- ifelse(catch_data$catchCategory=="C","KON",
                                    ifelse(catch_data$catchCategory=="R",
                                           "DIS",NA))

# updating surveygizmo data with existing laks-data from fiskeline - in case something has changed
ages$tripResp <- paste(ages$tripId,ages$sgId,sep="-")
ages$length <- ages$length/10
ages$speciesCode <- ages$species

# zeroCatches <- catch_data %>%
#   filter(number == 0 & speciesCode == "LKS" & catchCategory == "C") %>%
#   mutate(catchNum = as.numeric(catchNum))

catchInFiskeline <- catch_data %>%
  filter(tripResp %in% ages$tripResp) %>%
  select(tripId,sgId,respNum,dateGearStart,dateGearEnd,representative,treatment,stepNum,ageMeasureMethod,tripResp) %>%
  distinct()

catchInFiskeline2 <- left_join(catchInFiskeline,ages)

newCatches <- catch_data %>%
  filter(!tripResp %in% ages$tripResp) %>%
  mutate(catchNum = as.numeric(catchNum))


catch_data_out <- bind_rows(catchInFiskeline2,newCatches) %>%
    arrange(sgId) %>%
    select(sgId,tripId,respNum,catchNum,speciesCode,catchCategory,number,
           length,weight,code,otolith,age,treatment,representative,stepNum,
           landingCategory,ageMeasureMethod,dfuArea,dateGearStart,dateGearEnd) %>% 
  mutate(catchCategory = ifelse(landingCategory == "KON","C","R"))

# catch_data_out <- catch_data %>% 
#     arrange(sgId) %>% 
#     select(sgId,tripId,respNum,catchNum,speciesCode,catchCategory,number,
#            length,weight,code,otolith,age,treatment,representative,stepNum,
#            landingCategory,ageMeasureMethod,dfuArea,dateGearStart,dateGearEnd)

catch_data_fiskeline <- catch_data_out %>% 
  mutate(sampleType = "X",
         age = ifelse(age=="",NA,age))
    #filter(number>0)

# catch_data_out$treatment <- "UR"
# catch_data_out$representative <- "nej"
# catch_data_out$stepNum <- 0
# catch_data_out$landingCategory <- ifelse(catch_data_out$catchCategory=="C","KON",
#                                        ifelse(catch_data_out$catchCategory=="R",
#                                               "DIS",NA))
# catch_data_out$ageMeasureMethod <- "ØrestensAflæsning"
# catch_data_out$dfuArea <- "23"


# RespCatch ---------------------------------------------------------------
if (writeRespCatch == "yes"){
  respcatch <- full_join(resp_laks[,3:ncol(resp_laks)],catch_data_out,
                       by=c("sgId"="sgId","tripId"="tripId","respNum"="respNum"))
}
```


```{r writeOutput, echo=F,results='asis'}
# ###############################################################################
# 
# ###  Write output
# 
# ###############################################################################


path <- ""#"./data_out/laks/"


dateString <- format(Sys.Date(),"%d%m%y")

checkMissingValues <- function(df){
  totalnas <- 0
  for (col in colnames(df)){
    nas <- sum(is.na(df[[col]]))
    if (nas > 0){
      message(sprintf("%s %s value%s missing in %s\n",
                      nas,col,ifelse(nas==1," is","s are"),deparse(substitute(df))))
    }
    totalnas <- totalnas+nas
  }
  return(totalnas)
}

write.csv2 <- function(x,filename){
    write.csv(x,file = filename, row.names = F, na="",fileEncoding = "UTF-8")
  
   msg <- sprintf("%s genereret med %s rækker og %s kolonner. ",
              filename,nrow(x),ncol(x))
   
   return(cat(msg))
}
#

missingValuesInTrip <- checkMissingValues(trip_data_long2[,c("sgTRid","tripId","tripNum")])
missingCatchValues <- checkMissingValues(catch_data_fiskeline[,c("sgId","respNum","sampleType",
                                              "speciesCode","number",
                                              "dateGearStart","dateGearEnd",
                                              "treatment","representative",
                                              "stepNum","landingCategory",
                                              "ageMeasureMethod")])

if (missingValuesInTrip + missingCatchValues==0){
  
  if (writeCatchTrip %in% c("all","onlyNew")){
    
    if (writeCatchTrip == "onlyNew"){
      
          trip_db_out2 <- trip_data_long2 %>% 
            filter(!tripId %in% knownTrips$trip)
          
          catch_data_fiskeline2 <- catch_data_fiskeline %>% 
            filter(!tripId %in% knownTrips$trip)

    } else{
      trip_db_out2 <- trip_data_long2
      catch_data_fiskeline2 <- catch_data_fiskeline
    }
    
            cat("\\subsection{Catch}")
            write.csv2(catch_data_fiskeline2,
                       paste0(path,"REKREA_LAKS_CATCH_fiskeline_",dateString,".csv"))
            
            cat("\\subsection{Trip}")
            write.csv2(trip_db_out2,
                       paste0(path,"REKREA_LAKS_TRIP_fiskeline_",dateString,".csv"))
  }
}

# write.csv2(catch_data_out,
#            paste0(path,"REKREA_LAKS_CATCH_",dateString,".csv"))


# write.csv2(trip_data[order(trip_data$dateYMD),3:ncol(trip_data)],
#            paste0(path,"REKREA_LAKS_TRIP_",dateString,".csv"))

# write.csv2(trip_data_long2,
#            paste0(path,"REKREA_LAKS_TRIP_LONG_",dateString,".csv"))

if (writeResp=="yes"){
  
          cat("\\subsection{Resp}")
  write.csv2(resp_laks[,3:ncol(resp_laks)],
           paste0(path,"REKREA_LAKS_RESP_",dateString,".csv"))
}

if (writeRespCatch=="yes"){
          cat("\\subsection{RespCatch}")
  write.csv2(respcatch,
          paste0(path,"REKREA_LAKS_RESPCATCH_",dateString,".csv"))
}
```

```{r sanity_check, echo=F, warning=F, message=F, error=T, results = 'asis'}
cat("\\newpage \\section{Kvalitetstjek} ")

catch_db_fiskeline3 <- left_join(catch_data_fiskeline %>% select(-dfuArea), trip_data_long2) %>% 
  mutate(where = ifelse(tripId %in% knownTrips$trip,"FiskeLine","SurveyGizmo")) %>% 
  mutate(where = as.factor(where))

cat("\\subsection{Længde-vægt-plots} ")
cat("I de følgende længe-vægt-plots er de registrerede laks illustreret. De største outliers er fundet med cooks distance og bliver vist i en tabel under plottet med information om turnummer, respondetnummer og fangstnummer. Hvis outlieren allerede er i Fiskeline, kan man med fordel rette outlieren i fiskeline. Hvis outlieren er i SurveyGizmo, kan man med fordel rette outlieren i SurveyGizmo. \\newline")

for (sp in unique(catch_db_fiskeline3$speciesCode)){
  
  db_spec <- catch_db_fiskeline3 %>% 
    filter(speciesCode == sp) %>% 
    filter(!is.na(length) & !is.na(weight) & length!=0 & weight != 0) %>% 
    mutate(log_length = log10(length),
           log_weight = log10(weight))
  
  if (nrow(db_spec)>1){

    db_spec$cooksd <- cooks.distance(lm(log_length ~ log_weight, data=db_spec))

    db_spec[is.nan(db_spec$cooksd),"cooksd"] <- 1

    lim <- case_when(nrow(db_spec) < 10 ~ 3,
                     nrow(db_spec) < 100 ~ 5,
                     TRUE ~ 10)
     
     db_spec <- db_spec %>% 
       mutate(diffId = row_number(desc(cooksd)),
              dfuArea = as.character(dfuArea))
  
  outliers <- db_spec %>% filter(db_spec$diffId <= lim)
  
  db_spec2 <- db_spec %>% 
    group_by(where,dfuArea,length,weight) %>% 
    summarise(number = sum(number, na.rm=T))

  lwp <- ggplot(db_spec2, aes(x=length, y= weight))+
    geom_point(aes(col=where))
  
  # if (nrow(catch_db_fiskeline3[catch_db_fiskeline3$source=="SG"])>0){
  #   
  #   lwp <- lwp + geom_point(catch_db_fiskeline3[catch_db_fiskeline3$source=="SG"],
  #                           mapping = aes(x=length, y= weight),col="black")
  # }
    
    if (nrow(outliers)>0){
      lwp <- lwp + geom_label_repel(outliers,mapping = aes(x=length, y= weight,label=diffId))
    }
  
  lwp <- lwp +
    theme_bw() +
    labs(title = sp, x = "Length (cm)",y = "Weight (kg)",col="Datakilde") 
    
  
  plot(lwp)
  
  if (nrow(outliers)>0){
    
    o2 <- outliers %>%
      mutate(dfuArea = as.numeric(dfuArea)) %>% 
      select(diffId,sgId, tripId,respNum,catchNum,
             speciesCode,number,length,weight,interviewPerson,where) %>% 
      arrange(diffId)
    
    colnames(o2) <- c("Outlier","sgId","Tur","Respnr.","Fangstnr.","Art","Antal",
                      "Længde","Vægt","Observatør","Kilde")
      
    
    o2 %>% 
      kable(format = "latex",booktabs=T,longtable=T) %>% 
      kable_styling(latex_options = c("repeat_header"),
                  repeat_header_continued = "\\textit{(fortsætter på næste side)}",
                  repeat_header_text = sprintf("\\textit{(fortsat)}")) %>% 
      print()
    
  }
  
  }
}


printDataCheck <- function(df,noString){
  if (nrow(df)>0){
    df %>% 
      kable(format = "latex",booktabs=T,longtable=T) %>% 
      kable_styling(#latex_options = c("repeat_header"),
                    repeat_header_continued = "\\textit{(fortsætter på næste side)}",
                    repeat_header_text = sprintf("\\textit{(fortsat)}")#,
                    #full_width = T
                    ) %>% 
      row_spec(0, angle = 90)
  } else{cat(noString)}
  
  
}
cat("\\subsection{Registrerede arter}")
options(knitr.kable.NA = '')

spPerQtr <- catch_db_fiskeline3 %>% 
  left_join(species) %>% 
  mutate(spC = paste(speciesCode,dkName, sep = " - ")) %>% 
  group_by(year,quarterStart,spC) %>% 
  summarise(Antal = sum(number,na.rm=T)) %>% 
  spread(key = spC, value = Antal) %>% 
  rename(Kvartal=quarterStart,
         År=year) 
  # replace(is.na(.),"-") %>% 

printDataCheck(spPerQtr, "Ingen registrerede arter er indsamlet")

unknownSp <- catch_db_fiskeline3 %>% 
  filter(!speciesCode %in% species$speciesCode) 

printDataCheck(unknownSp, "Ingen registrerede arter er ukendte for fiskeline.")

cat("\\subsection{Arter pr. område}")

spPerArea <- catch_db_fiskeline3 %>% 
  left_join(species) %>% 
  mutate(spC = paste(speciesCode,dkName, sep = " - ")) %>% 
  group_by(tripId,interviewPerson,dfuArea,spC) %>% 
  summarise(Antal = sum(number,na.rm=T)) %>% 
  spread(key = spC, value = Antal) 
  # replace(is.na(.),"-") %>% 

printDataCheck(spPerArea, "Ingen registrerede arter er indsamlet")


cat("\\subsection{Check af unikke værdier}")
cat("\\subsubsection{Check af unikke værdier}")


doubleSgId <- catch_db_fiskeline3 %>% 
  group_by(sgId) %>% 
  summarise(TripIds = length(unique(tripId))) %>% 
  filter(TripIds > 1) 
  
printDataCheck(doubleSgId,"Ingen SurveyGizmo-id'er ser ud til at være knyttet til den samme respondent. \\newline ")
  
respCheck <- catch_db_fiskeline3 %>% 
  group_by(tripId,respNum) %>% 
  summarise(sgIds = length(unique(sgId))) %>% 
  filter(sgIds > 1)

printDataCheck(respCheck,"Ingen respondenter ser ud til at være knyttet til flere SurveyGizmo-id'er \\newline ")

sgIdCheck <- catch_db_fiskeline3 %>% 
  group_by(sgId) %>% 
  summarise(sgIds = length(unique(respNum))) %>% 
  filter(sgIds > 1)

printDataCheck(sgIdCheck,"Ingen SurveyGizmo-id'er ser ud til at være knyttet til flere respondenter. \\newline ")

duplicateTrips <- trip_db_out2 %>% 
  group_by(sgTRid) %>% 
  summarise(tripIds = length(unique(tripId))) %>% 
  filter(tripIds>1)

printDataCheck(duplicateTrips,"Ingen Ture ser ud til at være afviklet flere gange. \\newline ")

cat("\\subsection{Manglende værdier i trip}")
cat("Her vil de obligatoriske kolonner, som mangler data i Trip-filen bliver vist med antallet af manglende værdier. ")

for (col in colnames(trip_data_long2[,c("sgTRid","tripId","tripNum")])){
  
  a <- checkMissingValues(trip_data_long2[[col]])
  
  if (a > 0){
    cat(sprintf("Kolonne %s: %s manglende værdier \\newline ",col,a))
  }
}

cat("\\subsection{Manglende værdier i fangst-fil}")
cat("Her vil de obligatoriske kolonner, som mangler data i catch-filen bliver vist med antallet af manglende værdier. ")

for (col in colnames(catch_data_fiskeline2[,c("sgId","respNum","tripId","sampleType",
                                              "speciesCode","number",
                                              "dateGearStart","dateGearEnd",
                                              "treatment","representative",
                                              "stepNum","landingCategory",
                                              "ageMeasureMethod")])){
  a <- checkMissingValues(catch_data_fiskeline2[[col]])
  
  if (a > 0){
    cat(sprintf("Kolonne %s: %s manglende værdier \\newline ",col,a))
  }
}
```