---
fontsize: 12pt
geometry: margin=1in
header-includes:
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage{floatrow}
- \usepackage[T1]{fontenc}
- \usepackage[danish]{babel}
- \usepackage[utf8]{inputenc}
- \usepackage{graphicx}
- \floatsetup[table]{capposition=top}
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \fancyhf{}
- \usepackage[table]{xcolor}
- \usepackage{ragged2e}
- \usepackage{catchfile}
- \usepackage{array}
- \usepackage[export]{adjustbox}
- \usepackage{multirow}
- \linespread{1.15}
- \usepackage{tabularx}
- \usepackage{tcolorbox}
- \usepackage{lipsum}
output:
  pdf_document: default
  word_document: default
---



\renewcommand{\familydefault}{\sfdefault}
\sffamily

```{r define_input, echo=FALSE}

#Parameters
# animalID <- @paramAnimalID

animalID <- sample(1:7652670,size = 1)
# animalID <- 7224848

```


```{r set_libraries, include=FALSE}
if (!require(RODBC)) {
  install.packages("RODBC", repos="http://ftp.ussg.iu.edu/CRAN/")
  library(RODBC)
}
if (!require(dplyr)) {
  install.packages("dplyr", repos="http://ftp.ussg.iu.edu/CRAN/")
  library(dplyr)
}


```


```{r, include=F}
dbQuery <- paste0("SELECT an.[animalId]
      ,an.[year]
      ,an.[cruise]
      ,an.[trip]
      ,an.[tripType]
      ,an.[station]
      ,an.[dateGearStart]
      ,an.[speciesCode]
	  ,sp.dkName
      ,an.[sizeSortingEU]
      ,an.[sexCode]
      ,an.[individNum]
      ,an.[number]
      ,an.[length]
      ,an.[weight]
	  ,age.age
  FROM [FishLineDW].[dbo].[Animal] as an
  left join FishLineDW.dbo.Age as age
  on an.animalId = age.animalId
  left join FishLineDW.dbo.L_species as sp
  on an.speciesCode = sp.speciesCode
  where 
  --an.year = 2018 
 -- and
 an.animalId =	",animalID)

channel <- odbcConnect("FishlineDW")
animal <- sqlQuery(channel, dbQuery, stringsAsFactors=F)
close(channel)

```

\section{Information om id `r paste0(animalID)`}

```{r echo=F, eval=T,results='asis'}
# cat(paste0("\\section{Information om id ",animalID, "}"))

if (nrow(animal)>0){
  
  cat("\\begin{description}")
  
  for (col in 1:ncol(animal)){
    for (row in 1:nrow(animal)){
      cat(paste0("\\item[",names(animal)[col],"] ", animal[row,col], " "))
    }
  }
  
  cat("\\end{description}")
  
  write.table(animal, file=paste0("lookup_",animalID,".csv"), sep=",",
            row.names = FALSE, quote=FALSE)
  
} else {
  cat(paste0("Ingen information kan findes på animal-id ", animalID))
}

```


