---
header-includes:
- \usepackage{tabularx}
- \usepackage{booktabs}
- \usepackage{longtable}
output:
  pdf_document:
    latex_engine: xelatex
  fontsize: 12pt
geometry: top=0.2cm, bottom=1.2cm, left=0.5cm, right=0.5cm
---
  
  \renewcommand{\familydefault}{\sfdefault}
\sffamily


```{r define_input, echo=FALSE}


#Parameters
# year <- @paramYear
# cruise <- @paramCruise
# trip <- @paramTrip
# station <- @paramStation
# journal <- @paramJournal 
# species <- @paramSpecies

year <- 2020
cruise <- 'IBTS-1'
trip <- '1'
station <- '64'
journal <- ""
species <- "KUL"
```




```{r set_libraries, include=FALSE}

#Libraries
if (!require(sqldf)) {
  install.packages("sqldf", repos="http://ftp.ussg.iu.edu/CRAN/")
  library(sqldf)
}
if (!require(RODBC)) {
  install.packages("RODBC", repos="http://ftp.ussg.iu.edu/CRAN/")
  library(RODBC)
}
if (!require(knitr)) {
  install.packages("knitr", repos="http://ftp.ussg.iu.edu/CRAN/")
  library(knitr)
}
if (!require(kableExtra)) {
  install.packages("kableExtra", repos="http://ftp.ussg.iu.edu/CRAN/")
  library(kableExtra)
}
if (!require(tinytex)) {
  install.packages("tinytex", repos="http://ftp.ussg.iu.edu/CRAN/")
  library(tinytex)
}


# knit_hooks$set(document = function(x) {sub('\\usepackage[]{color}', '\\usepackage[table]{xcolor}', x, fixed = TRUE)})

```

```{r, echo=FALSE, message=FALSE, warning=FALSE}


channel <- odbcConnect("FishLineDW")
data <- sqlQuery(channel, paste("SELECT     Animal.animalId, Animal.year, Animal.cruise, Animal.trip, Animal.tripType, 
                                Animal.station, Animal.dateGearStart, Animal.dfuArea, Animal.statisticalRectangle,
                                Animal.speciesCode, Animal.landingCategory, 
                                Animal.representative, Animal.sizeSortingEU as sorting, Animal.sizeSortingDFU as opdeling, 
                                Animal.individNum, Animal.number, Animal.length, Animal.weight, Animal.sexCode, 
                                Animal.maturityIndex, Age.age, Sample.labJournalNum,Trip.harbourLanding as havn
                                FROM       Animal INNER JOIN
                                SpeciesList ON Animal.speciesListId = SpeciesList.speciesListId INNER JOIN
                                Sample ON SpeciesList.sampleId = Sample.sampleId INNER JOIN
                                Trip ON Sample.tripId = Trip.tripId LEFT OUTER JOIN
                                Age ON Animal.animalId = Age.animalId
                                WHERE      (Animal.year = (",year, ") AND 
                                Animal.trip = ('",trip,"') AND
                                Animal.cruise = ('",cruise,"') AND
                                Animal.station = ('",station, "') AND
                                Animal.speciesCode = ('",species, "') AND
                                Animal.individNum != 0  ) " ,sep=""), as.is = TRUE)                        
close(channel)

data$weight <- as.numeric(data$weight)

date <- format(as.Date(data$dateGearStart[1]), "%d-%m-%Y")

```


```{r, echo=FALSE, include=FALSE, cache=FALSE, warning=FALSE}

##make tex-table 1


data$labJournalNum[is.na(data$labJournalNum)] <- "-" 
journal <- data$labJournalNum[1]
data_table <- data[c("sorting", "opdeling", "individNum","length","weight","age","sexCode","maturityIndex","animalId")]
data_table2 <- data_table[order(data_table$sorting,data_table$individNum) ,]
data_table2$comment <- ""
data_table2[data_table2=="FALSE"] <- ""

data_table2[is.na(data_table2)] <- "-"

```

```{r}


# \setlength{\tabcolsep}{20pt}
# \renewcommand{\arraystretch}{1.2}
# \begin{tabularx}{\textwidth}{ l l l l l l}
# \textbf{Togt:} `r cruise`  & \textbf{Tur:} `r trip` & \textbf{Station:} `r station` & \textbf{Type:} `r data$tripType[1]` & \textbf{Dato:} `r date`\\
# \textbf{Art:} `r species`  & \textbf{Journal:} `r journal` & \textbf{Område:} `r data$dfuArea[1]` & 
#   \textbf{Square:} `r data$statisticalRectangle[1]` & \textbf{Havn:} `r data$havn[1]` \\
# \end{tabularx}
# 
# \vspace{0.5cm}

```




```{r,  echo = F, results = "asis", eval = T}


kableExtra::kable(
    data_table2,
    longtable = T,
    row.names = F,
    col.names = c(
      "Sort.",
      "Opdel.",
      "IndividNum",
      "Længde",
      "Vægt",
      "Alder",
      "Køn",
      "Moden.",
      "aninalId",
      "Kommentar"
    ),
    vline = ""
  ) %>%
kable_styling(full_width = F, position = "center") %>%
  column_spec(column = 1:9, width_max = "1cm") %>%
  column_spec(column = 10, width_min = "2cm") 


```



```{r, results = "asis", eval = F}

library(xtable)

options(xtable.comment = FALSE)

print(
  xtable(
      x = data_table2
      #align = c("l", rep("L{1cm}", ncol(data_table2)))
  ),
  
  #table.placement = "H",
  include.rownames = F,
  include.colnames = TRUE,
  booktabs = T,
  #tabular.environment = c("tabularx"),
  tabular.environment = "tabularx",
  width="\\textwidth" #,
  # floating = FALSE,
  #scalebox='0.75'
  
)

```




