---
fontsize: 11pt
geometry: top=2cm, bottom=2cm, left=1cm, right=2cm,headsep=1cm
header-includes:
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage[T1]{fontenc}
- \usepackage[danish]{babel}
- \usepackage[utf8]{inputenc}
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \fancyhf{}
- \fancyfoot{}
- \usepackage{multirow}
- \linespread{1.15}
- \usepackage{tabularx}
output:
  pdf_document: default
  word_document: default
---
  
  \renewcommand{\familydefault}{\sfdefault}
\sffamily



```{r , include=F}
# @paramCruise
# SELECT c.cruise, c.cruise
# FROM FishLineDW.dbo.Cruise c
# WHERE c.year = @paramYear
# 
# @paramTrip
# SELECT t.trip, t.trip
# FROM FishLineDW.dbo.Trip t
# WHERE t.year = @paramYear
#   AND t.cruise = @paramCruise
# ORDER BY t.trip 
# 
# @paramStation
# SELECT s.station, s.station
# FROM FishLineDW.dbo.Sample s
# WHERE s.year = @paramYear
#   AND s.cruise = @paramCruise
#   AND s.trip in (@paramTrip)
# ORDER BY s.station
# 
# 
# @paramSpecies
# SELECT A.speciesCode + ' - '+ ISNULL(s.dkName, ''), A.speciesCode
# FROM FishLineDW.dbo.Sample sa
# INNER JOIN FishLineDW.dbo.SpeciesList sp
#         ON sp.sampleId = sa.sampleId
# INNER JOIN FishLineDW.dbo.Animal A
#         ON A.speciesListId = sp.speciesListId
# LEFT OUTER JOIN FishLine.dbo.L_Species s
#         ON s.speciesCode = A.speciesCode
# WHERE A.year = @paramYear
#   AND A.cruise = @paramCruise
#   AND A.trip in (@paramTrip)
#   AND A.station in (@paramStation)
#   AND A.individNum != 0
# GROUP BY s.dkName, A.speciesCode
# ORDER BY A.speciesCode + ' - ' + ISNULL(s.dkName, '')
```



```{r define_input, echo=FALSE}


#Parameters
year <- @paramYear
cruise <- @paramCruise
trip <- c(@paramTrip)
station <- c(@paramStation)
species <- @paramSpecies

# year <- 2019
# cruise <- "BITS-1"
# trip <- c("1","2")
# station <- c("21","23","95","107","109")
# species <- "TOR"

stationSQL <- paste0(station,collapse = "','")
tripSQL <- paste0(trip,collapse = "','")
```

\lhead{\footnotesize Togt: `r cruise`, År: `r year`, Art: `r species` }
\rhead{\footnotesize Udskrevet: \today }
\fancyfoot[R]{\thepage}



```{r set_libraries, include=FALSE}
#Libraries
# try(detach("package:kableExtra", unload=TRUE))
if (!require(RODBC)) {
  install.packages("RODBC", repos="http://ftp.ussg.iu.edu/CRAN/")
  library(RODBC)
}

if (!require(kableExtra)) {
  install.packages("kableExtra", repos="http://ftp.ussg.iu.edu/CRAN/")
  library(kableExtra)
}

if (!require(dplyr)) {
  install.packages("dplyr", repos="http://ftp.ussg.iu.edu/CRAN/")
  library(dplyr)
}
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
channel <- odbcConnect("FishLineDW")
data <- sqlQuery(channel, sprintf("SELECT     Animal.animalId, Animal.year, Animal.cruise, Animal.trip, Animal.tripType, 
                                Animal.station, Animal.dateGearStart,Animal.dfuArea, Animal.statisticalRectangle,Animal.tripType,
                                Animal.speciesCode, Animal.landingCategory, 
                                Animal.representative, Animal.sizeSortingEU as sorting,
                                Animal.individNum, Animal.number, Animal.length, Animal.weight, Animal.sexCode, 
                                Animal.maturityIndex, Age.age,Age.genetics, Sample.labJournalNum,Trip.harbourLanding as havn
                                FROM       Animal INNER JOIN
                                SpeciesList ON Animal.speciesListId = SpeciesList.speciesListId INNER JOIN
                                Sample ON SpeciesList.sampleId = Sample.sampleId INNER JOIN
                                Trip ON Sample.tripId = Trip.tripId LEFT OUTER JOIN
                                Age ON Animal.animalId = Age.animalId
                                WHERE      (Animal.year = (%s) AND 
                                Animal.trip in ('%s') AND
                                Animal.cruise = ('%s') AND
                                Animal.station in ('%s') AND
                                Animal.speciesCode = ('%s') AND
                                Animal.individNum != 0  ) " ,
                                year,tripSQL,cruise,stationSQL,species), 
                 stringsAsFactors=FALSE)                        
close(channel)

date <- format(as.Date(data$dateGearStart[1]), "%d-%m-%Y")

```






```{r, echo=FALSE, include=FALSE, cache=FALSE, warning=FALSE}

##make tex-table 1
data$genetics[data$genetics==1 & !is.na(data$genetics)] <- "Ja"
data$genetics[data$genetics==0 & !is.na(data$genetics)] <- "Nej"
data$genetics[is.na(data$genetics)] <- "Nej"

data$labJournalNum[is.na(data$labJournalNum)] <- "-"
data$havn[is.na(data$havn)] <- "-"
data$comment <- ""
data$date <- format(data$dateGearStart,"%Y-%m-%d")
```

```{r, echo=F,warning=F,error=F,message=F,results='asis'}
data_out <- data %>% 
  select(cruise,trip,tripType,station,labJournalNum,dateGearStart,statisticalRectangle,dfuArea,havn,
         speciesCode,sorting,individNum,length,weight,age,sexCode,maturityIndex,genetics,
         animalId,comment,date)


for (st in sort(unique(data_out$station))){
  
  dt2 <- data_out %>% 
    filter(station==st) %>% 
    arrange(sorting,individNum)
  
  cat("\\setlength{\\tabcolsep}{20pt} \n")
  cat("\\renewcommand{\\arraystretch}{1.2} \n")
  cat("\\begin{tabularx}{\\textwidth}{ l l l l l l} \n")
  cat(sprintf("\\textbf{Togt:} %s  & \\textbf{Tur:} %s & \\textbf{Station:} %s &                 \\textbf{Type:} %s & \\textbf{Dato:} %s \\\\ \n",
              dt2$cruise[1],dt2$trip[1],dt2$station[1],dt2$tripType[1],
              dt2$date[1]))

  cat(sprintf("\\textbf{Art:} %s  & \\textbf{Journal:} %s & \\textbf{Område:} 
                  %s & \\textbf{Square:} %s & \\textbf{Havn:} %s \\\\ \n", 
    species,dt2$labJournalNum[1],dt2$dfuArea[1],dt2$statisticalRectangle[1],
    dt2$havn[1]))
  cat("\\end{tabularx} \n")
  
  
  dt3 <- dt2 %>% 
    select(sorting,individNum,length,weight,age,sexCode,maturityIndex,genetics,
           animalId,comment) %>% 
    data.frame()

  dt3[is.na(dt3)]<-"-"
  
  colnames(dt3) <- c("Sorte-ring","Indvid-nummer","Længde (mm)","Vægt (g)","Alder",
                      "Køn","Moden-hed","Gene-tik","Animal Id","Bemærk-ninger")

 
  a <- kable(dt3, escape = F, longtable = T, booktabs = T, linesep = "",
             col.names = c("Sorte-ring", "Indvid-nummer", "Længde (mm)", "Vægt
                           (g)","Alder", "Køn","Moden-hed", "Gene-tik", "Animal
                           Id", "Bemærk-ninger")) %>% 
    kable_styling(latex_options = c("striped","repeat_header", "hold_position")) %>%
    column_spec(1:8,width = "0.5cm") %>% 
    column_spec(9:10,width = "1cm") 

  cat(a)

  
  cat("\\newpage{}")
  
  
}

```

```{r, include=F}

write.table(data_out %>% select(-date) %>% arrange(trip,station,individNum),
  file = sprintf("genetik_%s_%s_%s_%s.csv",year,cruise,species,format(Sys.Date(),"%Y%m%d")),
  sep = "\t",na = "",row.names = F,col.names = T)

```



<!-- Genetik-rapport -->